### ISSUE TITLE
podboat incorrectly pulling queue files from sources other than queue

### ISSUE THREAD

**Issue by rowet** [newsboat/newsboat#554] opened 2019-06-27 02:39 UTC
When newsboat is given a new feed URL that it had never seen before, podboat will then add every mp3 URL in the entire feed history to the download queue, even though these queued downloads are not evident in the queue text file in the config directory.

As an example, I have added this URL in my URLs file: http://feeds.soundcloud.com/users/soundcloud:users:169741362/sounds.rss 

I enqueued none of the episodes via newsboat, but every episode ever published now shows up in podboat.
![Screenshot from 2019-06-26 22-34-17](https://user-images.githubusercontent.com/11742050/60229241-3b902f00-9863-11e9-98b9-10261d1c5bd3.png)

**Comment by Minoru** [comment] 2019-06-27 18:21
Does Podboat list the files that you had in the queue before?

Are you using XDG?
* If yes, can you take a look at ~/.newsboat/queue and confirm that it contains exactly the files you see in Podboat?
* If no, can you take a look at ~/.local/share/newsboat/queue and confirm that it contains exactly the files you see in Podboat?

So far, this looks like our new `ConfigPaths` is doing something wrong. Let's figure this out ;)

**Comment by rowet** [comment] 2019-06-27 18:24
The queue file is entirely empty. podboat is somehow pulling every entry on a new feed from the sqlite database. It is only ever a problem if you add a new feed.

I don't know what you mean by XDG.

**Comment by Minoru** [comment] 2019-06-27 18:34
Okay, so by "queue file" you mean ~/.newsboat/queue. Can you check if ~/.local/share/newsboat/queue exists, and what it contains?

Podboat doesn't use the database, the only source of URLs for it is the queue file. I'm suspecting that I broke something in the last release, and Newsboat started writing the queue to a different place, which Podboat now reads.

XDG is a specification of where to store files in user's directory. It's an alternative to dotfiles and dotdirs like ~/.newsboat. Newsboat supports both, defaulting to ~/.newsboat.

**Comment by rowet** [comment] 2019-06-27 18:37
Yes, I mean the queue file. It is empty. Where it is doesn't affect the observed behavior. podboat *must* be using the database because the one and only queue file is empty.

I moved the entire config directory from .newsboat to .config/newsboat. But that's irrelevant to this bug because the same behavior had been happening before almost every time I added a new feed with mp3 entries.

**Comment by Minoru** [comment] 2019-06-27 19:03
The file location is important here because I suspect that Newsboat and Podboat are using different locations. So I'll ask again: can you check ~/.local/share/newsboat/queue file, to see if it contains the links that Podboat displays?

> the same behavior had been happening before almost every time I added a new feed with mp3 entries.

Do you have [`podcast-auto-enqueue`](https://newsboat.org/releases/2.14.1/docs/newsboat.html#podcast-auto-enqueue) set to "yes"?

**Comment by Minoru** [comment] 2019-07-06 14:09
@rowet, ping?

**Comment by rowet** [comment] 2019-07-06 22:19
I did unwittingly have podcast-auto-enqueue set to "yes".

No, there were no queue files anywhere on the file system at all containing the links. podboat is absolutely pulling entries from the cache db in some cases.

**Comment by Minoru** [comment] 2019-07-07 09:38
Let's try an experiment. Please install `strace` (usually it's in a "strace" package) and run the following:

```
$ strace -o podboat.strace podboat
```

Then post the resulting podboat.strace file. (You can attach a file to a GitHub comment, just click on a line between comment's input field and "Comment" button).

That file contains a list of all system calls that Podboat did, including `open()`. This way, we can figure out what locations Podboat is reading.

**Comment by Minoru** [comment] 2019-07-11 17:06
@rowet, ping? Sorry for not getting out of your hair yet, but I can't do anything about this issue until I reproduce it locally, or otherwise figure out what exactly went wrong (code-wise, not in terms of what a user can observe).

**Comment by rowet** [comment] 2019-07-12 03:54
I have since reinstalled my operating system, upgrading to fedora 30, and am using the podboat in the fedora repositories. The problems no longer manifest. I had been using podboat compiled from source on fedora 28.

**Comment by Minoru** [comment] 2019-07-12 18:16
Oh, all right then. Thanks for tolerating my persistence for this long :)

I'm closing this now because there is nothing we can do about this, but if anyone runs into this issue in the future, I'm ready to re-open and investigate further—just leave a comment here.

**Closed by Minoru** 2019-07-12 18:16 UTC
Labels: bug, cannot-reproduce
