### ISSUE TITLE
Feed producing duplicates

### ISSUE THREAD

**Issue by q3cpma** [newsboat/newsboat#256] opened 2018-08-23 10:01 UTC
**Newsboat version (copy from `newsboat -v`)**:
```
newsboat 2.10.2 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2017 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017 Newsboat contributors

newsboat is free software and licensed under the MIT License.
Type `newsboat -vv' for more information.

newsboat 2.10.2
System: Linux 4.18.3-gentoo (x86_64)
Compiler: g++ 6.4.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.61.0 OpenSSL/1.0.2o zlib/1.2.11 (compiled with 7.59.0)
SQLite: 3.23.1 (compiled with 3.23.1)
libxml2: compiled with 2.9.8
```

This feed (https://git.videolan.org/?p=x264/x264-sandbox.git;a=atom) produces some duplicates for older entries everytime it's updated, leading to something like this https://my.mixtape.moe/fkxksf.png
Any idea about why, and how to fix it?

**Comment by Minoru** [comment] 2018-08-23 19:13
Hi! Looking at the feed's code, I don't see any obvious reasons for such behaviour. I added it to my own Newsboat and will get back to you on Sunday. With any luck, 2 days should be enough to reproduce this.

**Comment by q3cpma** [comment] 2018-08-23 20:30
On Thu, Aug 23, 2018 at 07:15:26PM +0000, Alexander Batischev wrote:
> Hi! Looking at the feed's code, I don't see any obvious reasons for such behaviour. I added it to my own Newsboat and will get back to you on Sunday. With any luck, 2 days should be enough to reproduce this.

Thanks for trying. Hope there'll be enough commits for this to happen.

**Comment by Minoru** [comment] 2018-08-26 11:01
No commits over the last few days. I'll check back in two weeks.

**Comment by Minoru** [comment] 2018-09-09 10:00
Wow, it's been exactly two weeks, and the new commits just appeared!

I see the "duplicates", though it's wrong to call them that—really it's new items with the same text as some old items. Newsboat distinguishes items by their "GUIDs", which in this case include the commits' SHA1. Apparently the author cherry-picked or rebased some old commits, which changed their SHA1 but not their commit messages. The old items aren't present in the feed anymore, but Newsboat still has them, so it displays them.

This is not a bug in Newsboat itself, and there's nothing we can really do about it, so I'm going to close the issue.

**Closed by Minoru** 2018-09-09 10:00 UTC
Labels: bug, to check
