### ISSUE TITLE
Newsboat crashes at startup with "Segmentation fault: 11" error message.

### ISSUE THREAD

**Issue by Spreadcat** [newsboat/newsboat#2143] opened 2022-08-05 09:59 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

```bash
$ news -v
newsboat 2.20.1 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2020 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2020 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

newsboat 2.20.1
System: Linux 5.14.18-100.fc33.x86_64 (x86_64)
Compiler: g++ 10.2.1 20200723 (Red Hat 10.2.1-1)
ncurses: ncurses 6.2.20200222 (compiled with 6.2)
libcurl: libcurl/7.71.1 OpenSSL/1.1.1l-fips zlib/1.2.11 brotli/1.0.9 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 (compiled with 7.71.1)
SQLite: 3.34.1 (compiled with 3.32.3)
libxml2: compiled with 2.9.10
```

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
# Newsboat config file
# Ansible managed

auto-reload no
browser firefox
cache-file /data/sync/sources/newsbeuter/cache.db
cleanup-on-quit yes
display-article-progress yes
download-timeout 10
history-limit 0
ignore-mode download
keep-articles-days 30
macro o set browser "elinks %u"; open-in-browser ; set browser "firefox %u"
max-items 1000
refresh-on-startup yes
reload-threads 4
reload-time 23
save-path /data/sync/sources/newsbeuter/saved_articles
show-read-feeds no
feed-sort-order title
```

Steps to reproduce the issue:

1. Start newsboat

**Other info you think is relevant**:

* Due to similarities, I've performed the described steps [in this comment](https://github.com/newsboat/newsboat/issues/1133#issuecomment-671552859). These are the results

  1. remove `/data/sync/sources/newsbeuter/cache.db` and start Newsboat

     Newsboat still fails with the same error.

  2. remove cache.db again, edit your urls file to contains a single feed https://newsboat.org/news.atom, and start Newsboat;

     Newsboat starts, but shows no feeds or unread articles.

  4. restore cache.db and urls files, remove ~/.config/newsboat/config, and start Newsboat.

     Newsboat starts and shows all the feeds and articles, also some feeds that had been removed weeks ago (IIRC)

* Removing the config parameter `feed-sort-order title` let's newsboat start up again. After that the parameter can be added again and newsboat still will start up again.

**Comment by juntuu** [comment] 2022-08-07 11:09
This might be related to #2101 since you have `refresh-on-startup yes` in your config.

**Comment by Spreadcat** [comment] 2022-08-08 08:58
I have disabled `refresh-on-startup yes` on one of my hosts and will monitor it's behavior.
I've read through #2101, but I'm not convinced yet, that's the same/similar issue. The app is occasionally crashing before I even get to see the list of hosts. As soon as the TUI has been set up, it's running stable, no matter how often I refresh.

I'll monitor this change for a week and report in as soon as the issue occurs again.
If you don't hear anything from me within a week, assume the issue has been fixed and just close it if you like.

regards

**Comment by Minoru** [comment] 2022-08-10 20:29
Thanks for the report! I reproduced this with 2.20.1 (built with Rust 1.44.1 because Rust 1.62.1 fails to compile lexical-core), but failed to reproduce this with 331176fdd9fdbd876f37b33f22a1a7054a13b2f0 (current master).

2.20.1 doesn't always crash, but seems to crash more often if I start with an empty cache file.

Stacktraces show concurrent access to `FeedContainer::feeds`, which wasn't fully protected by a mutex in 2.20.1

Need to bisect this to figure out when we fixed it, and how. I'll keep this issue open until then.

**Comment by Minoru** [comment] 2022-08-10 21:10
Oh, thanks Dennis! The backtrace in the PR looks exactly like the one I saw in 2.20.1 today, so I'm confident it's indeed the fix. Closing then.

@Spreadcat `refresh-on-startup no` should fix this for you then. You can re-enable the setting once you've upgraded to 2.21 or newer.

**Closed by Minoru** 2022-08-10 21:10 UTC
Labels: bug

**Comment by Micronarrativ** [comment] 2022-08-11 18:45
@Minoru I can confirm that I didn't see any further crash after removing the parameter from the config. Thanks for the help.

**Comment by Spreadcat** [comment] 2022-08-11 18:46
@Minoru I can confirm that I didn't experience any further crashes after I've removed the parameter from the config. Thanks for the help.
