### ISSUE TITLE
Confusion when executing macros with read articles in view

### ISSUE THREAD

**Issue by tonycpsu** [newsboat/newsboat#70] opened 2017-11-25 17:20 UTC
I'm running newsboat r2.10.1-104-g5a68.  When I'm browsing unread articles, but with some read articles in view (`show-read-articles true`), I'm finding that executing macros results in an inconsistency between the article I have selected and the one that gets passed to the macro.

What seems to happen is that the selection is indexed by offset from the beginning of the list, but it seems to skip over read articles, even though they're visible.  So if it's like this:

    **read article 1 **
    **read article 2 **
    **unread article 1**  <--- cursor selection
    **unread article 2**
    **unread article 3**

and I run a macro, it passes the URL of `**unread article 3**`, where I expect it to be `**unread article 1**`.

**Comment by Minoru** [comment] 2017-11-26 16:25
Sorry, I can't reproduce that.

Here's the config I used:
```
show-read-articles true
browser "echo %u"
macro o open-in-browser
```

Here's the url file:
```
file://data/70.feed.xml
```

The `data/70.feed.xml` is a copy of `test/data/rss.xml` from the repo (you can [download it](https://raw.githubusercontent.com/newsboat/newsboat/5a6827d615a750a17630523133f278ed4113a10f/test/data/rss.xml) without cloning the whole repo).

The steps:
1. Start Newsboat: `./newsboat --cache-file=data/70.cache.db --url-file=data/70.urls --config-file=data/70.config`
2. Press `r` to reload the feed (there's only one, obviously).
3. `ENTER`, then mark two items as read by pressing `N` twice.
4. Press `,o` to invoke the macro. Press `ENTER`, the "Link" in the header says `http://aksmoblog.blogspot.com/2006/09/maronistand-im-spaetsommer.html`—should see the same in the terminal once Newsboat is closed.
5. Quit article view and then the Newsboat.
6. Observe the output in the terminal:
```
Starting newsboat r2.10.1-104-g5a68...
Loading configuration...done.
Opening cache...done.
Loading URLs from data/70.urls...done.
Loading articles from cache...done.
http://aksmoblog.blogspot.com/2006/09/maronistand-im-spaetsommer.html
Cleaning up cache...done.
```

I suspect you might have something else in your config, but I have no idea what it might be. Can you try and trim down your config until the problem disappears? By working out the minimal config that reproduces the problem, it'll be possible to understand what's going on.

@polyzen, you've upvoted the first post—does it mean you've seen that problem as well?

**Comment by tonycpsu** [comment] 2017-11-26 18:01
I figured it out -- yes, it's config-specific, so I apologize for not including my config in the first place.

To reproduce with your minimal configuration, add the following to the 70.urls file:

    "query:Unread Articles:unread = \"yes\""

and replace the macro with:

    macro o set browser "/bin/echo %u" ; open-in-browser ; set browser "echo %u"

Also, contra what I said in my bug report, set `show-read-articles` to `false`.  I was manually toggling it with the `l` key while trying to reproduce the bug and misstated what the value should be.

With this config, I get:

    http://aksmoblog.blogspot.com/2006/09/kurios.html

as output instead of:

    http://aksmoblog.blogspot.com/2006/09/maronistand-im-spaetsommer.html

You should also note that the shell command seems to force a "refresh" of the unread articles view that hides the read items, which seems like a likely culprit for the focused article being out of sync when the macro is called.

**Comment by Minoru** [comment] 2017-11-26 18:17
Okay, I reproduced it. You seem to be spot on with your observation here:

> You should also note that the shell command seems to force a "refresh" of the unread articles view that hides the read items, which seems like a likely culprit for the focused article being out of sync when the macro is called.

Need to find out how macros work, probably I just need to call some function a bit earlier. Thanks for the report!

**Comment by polyzen** [comment] 2017-11-26 18:40
@Minoru, this might be the issue I'm having. Here's what happening:

1. Disable `show-read-feeds`
2. Enter the feed at the bottom of the feed list
3. Mark its articles as read
4. Go back to the feed list
5. Enter the bottom feed (that was second from the bottom previously) while it's still highlighted
6. The feed that you had just marked as read is shown instead

**Comment by Minoru** [comment] 2017-11-26 19:05
@polyzen, [I couldn't reproduce](https://asciinema.org/a/VHPuAum6RsmVFJf1LlmtquTah). What version are you using? Anything other than `show-read-feeds false` in your config?

**Comment by polyzen** [comment] 2017-11-26 19:09
https://github.com/polyzen/dotfiles/blob/workstation/.config/newsboat/config

The `ignore` config has my `ignore-article` options.

**Comment by Minoru** [comment] 2017-11-26 21:10
Don't see anything obviously relevant in your config.

Have you watched my Asciinema recording? No errors on my part there?

STFL version might be important here; can you shore it, please?

I'll retry tomorrow with 2.10.1, and will split this into a different issue (because at least the symptoms are different, and merging is easier then splitting).

--
Regards,
Alexander Batischev

**Comment by polyzen** [comment] 2017-11-26 21:14
> Have you watched my Asciinema recording? No errors on my part there?

Yes, and no errors.

> STFL version might be important here; can you shore it, please?

0.24 from the Arch Linux repos.

**Comment by dennisschagt** [comment] 2021-09-17 18:05
It looks like this issue has been resolved. (I can reproduce it on r2.10.1 but can't reproduce it on current master).
Git bisect points to https://github.com/newsboat/newsboat/commit/65f6f99a4220d81785fb31a0f64feca02265e106 which is included since newsboat r2.22.

**Comment by tonyc-blastpoint** [comment] 2021-09-17 19:17
Yeah, I noticed this problem went away a while back and I forgot to post about it. :)

**Comment by dennisschagt** [comment] 2021-09-17 19:18
Thank you for the confirmation!

**Closed by dennisschagt** 2021-09-17 19:18 UTC
Labels: bug
