### ISSUE TITLE
newsboat doesn't store similar looking urls

### ISSUE THREAD

**Issue by whatapleasantsurprise** [newsboat/newsboat#1645] opened 2021-05-23 20:21 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
newsboat 2.23.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2021 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2021 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

newsboat 2.23.0
System: Linux 5.12.5-zen1-1-zen (x86_64)
Compiler: g++ 10.2.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.76.1 OpenSSL/1.1.1k zlib/1.2.11 zstd/1.5.0 libidn2/2.3.1 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 (compiled with 7.75.0)
SQLite: 3.35.5 (compiled with 3.35.2)
libxml2: compiled with 2.9.10
```
Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
auto-reload no

bind-key j down
bind-key k up
bind-key j next articlelist
bind-key k prev articlelist
bind-key G end
bind-key g home
bind-key u pageup
bind-key d pagedown
bind-key l open
bind-key h quit

browser /bin/false
macro , open-in-browser
macro m set browser "i3 exec mpv" ; open-in-browser ; set browser /bin/false
macro l set browser "i3 exec lbry" ; open-in-browser ; set browser /bin/false
```

Steps to reproduce the issue:

1. To the urls file add, for example:
```
https://lbryfeed.melroy.org/channel/eevblog
https://lbryfeed.melroy.org/channel/odysee/eevblog
```

2. Reload the feeds, both should be loaded

3. Close and then open newsboat

4. Only one of the two urls will have content

**Other info you think is relevant**:

**Comment by Minoru** [comment] 2021-05-23 20:30
Thanks for the report! We already have an issue for this, so I'm closing this one as a duplicate of #898.

**Closed by Minoru** 2021-05-23 20:30 UTC
