### ISSUE TITLE
Executing a command removes filter view

### ISSUE THREAD

**Issue by tsipinakis** [newsboat/newsboat#607] opened 2019-08-17 06:57 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: 2e3d11b028fb6cfd9c32452581bcbec7e3c0de2f

Steps to reproduce the issue:

1. Enter any feed and add a filter (F)

2. Open the command line and run any command (`set reload-time=15` for example)

The filter will be removed and the original feed will be shown.

**Comment by Minoru** [comment] 2019-08-24 13:17
#612 shows that the filter is removed in `set_redraw` overloads (for [FeedListFormAction](https://github.com/newsboat/newsboat/blob/cacbe32b10d6e4197c8b50a1feb347214414b871/include/feedlistformaction.h#L30) and [ItemListFormAction](https://github.com/newsboat/newsboat/blob/cacbe32b10d6e4197c8b50a1feb347214414b871/include/itemlistformaction.h#L29) respectively). I think these methods reset `apply_filter` because user might have changed `show-read-feeds`/`show-read-articles` setting manually; in that case, the FormAction has to show or hide some items. Here's how to reproduce that:

1. start Newsboat (with empty config, so `show-read-feeds` is set to its default `yes`);
2. type `:set show-read-feeds no`
3. observe that feeds with no unread items are hidden now.

Same thing for the article view. That would be broken if #612 was to be merged. Let's go back to the drawing board.

Note that `show-read-{feeds,articles}` is implemented in terms of filters; e.g. `toggle-show-read-feeds` simply adds or removes a predefined filter. In other words, pressing `l` always removes current filter and replaces it with something else. Since no-one complained about this, let's assume this is a correct behaviour, and preserve it. This means there are three states for {Feed,Item}ListFormAction: "show everything", "show unread", and "show matching user's filter". Right now we have a single `bool apply_filter` to distinguish between those, which it clearly can't do.

We could add yet another `bool`, but that would create *four* states, it'll be harder to understand the connection (there would be three fields in the play now), and harder to keep that correct. I suggest replacing the existing `bool` with an `enum class`.

**Comment by tsipinakis** [comment] 2019-08-24 15:03
>  I think these methods reset apply_filter because user might have changed show-read-feeds/show-read-articles setting manually

Ooops, I missed that thanks for pointing it out!

> I suggest replacing the existing bool with an enum class.

That would work but we would be duplicating the state. The `show-read-{feeds,articles}` value is already saves in the config file, IMO duplicating that would just be more complexity on top. I took a different approach and swapped `apply_filter` to mean `is a custom filter being used?` and created a `is_filtered` function to do the actual logic.

See [here](https://github.com/tsipinakis/newsboat/commit/606d23d182439404a9d5d9cc7177e32505f777f4).

> pressing l always removes current filter and replaces it with something else. Since no-one complained about this, let's assume this is a correct behaviour, and preserve it.

I was wondering about this, it seems a bit backwards this way but it's acceptable. Thanks for clearing that up.
But, if we regard `show-read-feeds` as a filter it's still inconsistent that `clear-filter` does not reset it. 

Actually, looks like that differs between the lists as well. It clear-filter does remove it for the itemlist

https://github.com/newsboat/newsboat/blob/cacbe32b10d6e4197c8b50a1feb347214414b871/src/itemlistformaction.cpp#L770-L774

But not for the feedlist

https://github.com/newsboat/newsboat/blob/cacbe32b10d6e4197c8b50a1feb347214414b871/src/feedlistformaction.cpp#L455-L461

The implementation linked above also fixes this since apply_filter isn't used to indicate that options value anymore.

**Comment by Minoru** [comment] 2019-08-24 15:46
> That would work but we would be duplicating the state.

You're right. Let's go with your approach then!

I didn't think of clear-filter. Hmm. It saddens me that we expose what is essentially an implementation detail. It's also not clear why we even use `Matcher` when we could just call `unread()` on `RssItem`s and `total_unread_count` on `RssFeed`s, and show/hide them based on the result. If we used those methods, we would decouple filters from `show-read-*`, and get two `bool`s: `apply_filter` and `show_read`. That new approach will also play nicely when we finally add the ability to apply filters to the result of previous filters (just like we do for search).

Yes, that'd break `toggle-show-feeds`, but it could be argued that its current behaviour is a result of a hack. The new implementation can also be defended on the ground that it's more orthogonal, giving users more choice of what they want to happen. The old behaviour can be emulated with a `macro l clear-filter; toggle-show-read-feeds`.

What do you think of that?

**Comment by tsipinakis** [comment] 2019-08-25 08:14
> It's also not clear why we even use Matcher when we could just call unread() on RssItems and total_unread_count on RssFeeds, and show/hide them based on the result

You're right that's a good approach to resolve this, implemented in #615

**Closed** 2019-08-25 09:42 UTC
Labels: bug
