### ISSUE TITLE
Browser exit codes overflow on the byte boundary

### ISSUE THREAD

**Issue by tsipinakis** [newsboat/newsboat#855] opened 2020-04-01 18:59 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: d72a990

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
browser "./success"
```
where `success` is the following program:
`int main() { return 256; }`

Steps to reproduce the issue:

1. Open any article in the browser

On d72a990 newsboat will think the browser succeeded and will mark the article as read. On the initial implementation of this feature in 2.18 this would've failed with `Browser returned error code 256`

This was brought up by Hund on IRC. From @Minoru:
> Minoru: main() returns int, but according to https://en.wikipedia.org/wiki/Exit_status#POSIX not all library functions can return the whole thing.

I'm not sure which of the two behaviours we actually want here.

**Comment by tsipinakis** [comment] 2020-04-01 21:21
I forgot to mention, this was introduced in #799 according to a bisect.

**Comment by Minoru** [comment] 2020-06-17 17:20
> On the initial implementation of this feature in 2.18 this would've failed with Browser returned error code 256

I can't reproduce this on https://github.com/newsboat/newsboat/commit/a4ca71a5d7a28e2eb9d137d7921ff54d34d5ee65. To get this error message, I have to `return 257` instead. Please check again, I'm pretty sure it's impossible to get an error message by returning 256.

Understanding this took a bit of digging, and here's my findings (or, rather, learnings).

[system(3)](https://man7.org/linux/man-pages/man3/system.3.html), which we use to invoke the browser, doesn't actually return the exit code of the program as-is. Instead, it passes on a value returned by [waitpid(2)](https://man7.org/linux/man-pages/man2/waitpid.2.html). That value is an `int` containing not just the exit code, but also some flags indicating e.g. if the process died because of a signal, and if so, which one. It's impossible to fit an `int` *and* some flags into an `int`, so waitpid(2) only returns the lowest 8 bits of what `main()` returns.

(The return value of `system()` must be examined using macros like `WEXITSTATUS`, but all we did is check if it's -1 or not. That's an epic failure on my part as a reviewer and as a systems programmer: I know I should be extra careful with C library calls and OS syscalls, and the manpage for `system()` is only one screen long, yet I managed to completely gloss over this.)

That same manpage also describes [waitid(2)](https://man7.org/linux/man-pages/man2/waitpid.2.html) which *does* return the whole `int` that `main()` returns. There are a couple problems with that system call, though:

1. despite being a part of POSIX since 2008, and SUS even longer than that, waitid() is absent from OpenBSD and macOS. It *is* available on Linux, [FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=waitid&sektion=2&manpath=), and [NetBSD](https://netbsd.gw.com/cgi-bin/man-cgi?waitpid+2.i386+NetBSD-8.1), but I [saw it mentioned](https://github.com/rust-lang/libc/pull/520#issuecomment-284248759) that FreeBSD only has it in the Linux compatibility layer, i.e. native FreeBSD apps can't use it;

2. POSIX [mandates](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_08_02) that the shell ought to use `wait()`, which implies that any conforming shell only sees the lowest 8 bits of the exit code. I verified that ZSH 5.8, BASH 5.0.16, and dash 0.5.10.2 all ignore the higher bits, both in their `$?` variable and when evaluating and-lists (`cmd1 && cmd2`).

So on one hand, we technically *can* support programs that return codes outside the [0; 255] range, but there is little practical benefit to that, since Newsboat's behaviour will then be inconsistent with shells. Years of living with wait() even made BSDs standardize some exit codes, see [sysexits(3)](https://man.openbsd.org/sysexits), so I doubt there are any hotshots out there who risk returning anything outside of the conventional range.

With that, I declare this a "wontfix" since the behaviour is intentional. Thanks for filing this, though; digging into this certainly was an extremely valuable lesson for me.

**Closed by Minoru** 2020-06-17 17:20 UTC
Labels: bug

**Comment by tsipinakis** [comment] 2020-06-17 17:43
> I can't reproduce this on a4ca71a. To get this error message, I have to return 257 instead. Please check again, I'm pretty sure it's impossible to get an error message by returning 256.

I just tested it, you're right. I guess I got confused with the error message when I was writing this, returning 257 gives an error saying it returned 256. :/

**Comment by Minoru** [comment] 2020-06-17 17:53
Thanks for checking! Now I can rest assured I've got the correct picture of the situation :)

> returning 257 gives an error saying it returned 256. :/

That's easy to explain: wait() encodes the exit code into the second byte. 257 % 256 = 1, so wait() would return 0x00000100 -- which is 256.

This issue is about the range for exit codes, so I concentrated on that. In #825, I'll have more to say about us using the whole result of system() instead of just the second byte.
