### ISSUE TITLE
Tagged article not ignored

### ISSUE THREAD

**Issue by mikaelz** [newsboat/newsboat#2925] opened 2024-11-24 09:03 UTC
**Newsboat version**: 2.37

Config file:

```
ignore-mode "display"
ignore-article "*" "tags =~ \"Prepping\" and (title =~ \"pets|mylar\")
# or
ignore-article "*" "tags # \"Prepping\"" "title =~ \"pets|mylar\""
# or
ignore-article "*" "tags =~ \"Prepping\"" "title =~ \"pets|mylar\""
```

Hi, the above filter doesn't filter out article in feed tagged with Prepping and in title string pets.
Please help. Tried multiple version of filter expression, but without luck.

PS: Also add working example into docs at https://newsboat.org/releases/2.37/docs/newsboat.html#_killfiles

**Comment by juntuu** [comment] 2024-11-24 15:13
Looks like tags are not available when the expression is checked, so the first condition will always be false.
I think this could be changed in Newsboat, or documented clearly. At least I didn't see it mentioned in the docs.

https://github.com/newsboat/newsboat/blob/b080c3fcdf12f1d9324f6235cdc00eef6732f88e/src/controller.cpp#L850-L853

Also, the examples seem to have small syntax errors:
- the first is missing a closing `"` from the end
- others are two separate strings, these should be one string joined with `and` operator like the first

If tags would be available, any of those examples should work after fixing the syntax.

**Comment by juntuu** [comment] 2024-11-24 15:25
Hmm, found an earlier issue on this: duplicate of #101

**Closed** 2024-11-25 17:37 UTC
