### ISSUE TITLE
bookmark-cmd file is always loaded from default config file despite providing separate config file using -C

### ISSUE THREAD

**Issue by BombchuLink** [newsboat/newsboat#1775] opened 2021-09-16 03:58 UTC
It's only bookmark-cmd that's being an issue, it loads the rest of the config file provided with -C as you would expect

**Comment by Minoru** [comment] 2021-09-16 09:41
I couldn't reproduce this on current `master` (e6105033129a3dd853bde8fd11a1e2a9fd574f38). What I did is:

1. created /dev/shm/config file containing just one line: `bookmark-cmd "/usr/bin/echo custom"`
2. added the following line to the end of ~/.newsboat/config: `bookmark-cmd "/usr/bin/echo default"`
3. started Newsboat with the custom config: `./newsboat -C /dev/shm/config --cache-file=/dev/shm/cache.db`
4. navigated to an item, pressed `^B` to bookmark it, and kept pressing Enter to go through all the dialogs

As a result, I got this error message:

```
Error while saving bookmark: custom https://abstrusegoose.com/611 the glorious new master race  Abstruse Goose
```

Which is expected because any output from the bookmark command is considered an error. The URL and other stuff were returned because they were passed as arguments into `echo`.

@BombchuLink, I don't see a way for current Newsboat to behave as you describe. What version are you running? Do the steps I provided look similar to what you're doing? Perhaps you could follow the issue template and provide a way to reproduce this? ;)

**Comment by BombchuLink** [comment] 2021-09-19 04:52
I have no idea how, but apparently in my launcher script, I just messed up using " and variables properly. After simplifying things, and rebuilding the script it worked. (don't you love how you spend 5 hours working on something, submit a bug report, then 20 minutes of work later figure out it was your own fault all along? ;_; )

**Comment by Minoru** [comment] 2021-09-19 19:42
Phew! I feel sorry for you, but I'm also happy this isn't one of those "mystery bugs" where I never learn the cause ^_^ Happy we can close this now. Thanks for writing back! :+1:

**Closed by Minoru** 2021-09-19 19:42 UTC
Labels: bug, cannot-reproduce
