### ISSUE TITLE
Youtube xml links crash newsboat

### ISSUE THREAD

**Issue by DeathKhan** [newsboat/newsboat#1593] opened 2021-04-15 19:49 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
https://www.youtube.com/feeds/videos.xml?channel_id=UC7YOGHUfC1Tb6E4pudI9STA
```

Steps to reproduce the issue:

1. Import youtube xml link

2. try opening one of the youtube 'articles'

**Other info you think is relevant**:

**Comment by Minoru** [comment] 2021-04-15 19:56
Works for me on 2046488265aba232c81c3e1a086a8a7cbf2fcec8. What version are you running, @DeathKhan? Can you show your *actual* config (right now, you show your urls file instead)?

**Comment by crobs** [comment] 2021-06-23 17:59
This is happening for me as well, with a blank config file and a single YouTube feed link (in the format above) in my urls file.
It only crashes on some YouTube rss feeds, not all nor the majority. It also happens on some BitChute rss links.
I'm on Arch linux and version 2.24.0 of newsboat.

**Comment by crobs** [comment] 2021-06-24 00:38
Ok, so it may actually be the terminal crashing and not newsboat. When these crashes occur, the terminal goes down with it. I don't know if a program running inside a terminal can cause the terminal itself to crash?
I'm using the st terminal and I've discovered that these crashes do not occur in the linux console, xterm, or urxvt. So it seems to be something specific to st.

**Comment by crobs** [comment] 2021-06-24 00:46
Ok, it is indeed an st thing, caused by emojis in the article. I fixed it by installing ttf-symbola from the AUR as per the Archwiki page on st.

**Comment by Minoru** [comment] 2021-06-24 15:56
Oh, thanks! This perfectly explains why I was unable to reproduce. Even now, if I run Newsboat in st and open one of the feeds you mention, it doesn't crash — I probably have an appropriate font installed already, since I do see emojis displayed.

Thanks for resolving the mystery, @crobs! :+1:

**Closed by Minoru** 2021-06-24 15:56 UTC
Labels: bug, cannot-reproduce
