### ISSUE TITLE
enqueue fails with invalid url

### ISSUE THREAD

**Issue by MaryJo42** [newsboat/newsboat#252] opened 2018-08-18 08:26 UTC
newsboat 2.10.2 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2017 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017 Newsboat contributors

newsboat is free software and licensed under the MIT License.
Type `newsboat -vv' for more information.

newsboat 2.10.2
System: Linux 4.15.0-32-generic (x86_64)
Compiler: g++ 7.2.0
ncurses: ncurses 6.1.20180127 (compiled with 6.0)
libcurl: libcurl/7.58.0 GnuTLS/3.5.18 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3 (compiled with 7.57.0)
SQLite: 3.22.0 (compiled with 3.21.0)
libxml2: compiled with 2.9.4
Steps to reproduce the issue:
Replaced newsbeuter with newsboat.
Now I cannot enqueue video podcasts from feeds where it worked in newsbeuter previously; it fails with
Invalid URL: ''
1. https://github.com/newsboat/newsboat/issues/115 - It appears to be this problem of mimetypes again as when I manually enqueue, podboat downloads fine.
Problem happens with .m4a, .mkv and .mp4 feeds.
Example: Youtube Subscriptions - which were fine in newsbeuter, are all now 'invalid urls'
"https://www.youtube.com/watch?v=e0xGHf8o-9k" - "How Brexit could create a crisis at the Irish border-e0xGHf8o-9k.mkv"
Same happens with subscription podcasts that I cannot give you an example of but end in .m4a.
I have a workaround of 'manually enqueue' or youtube-dl so this is not a pressing bug.
Thanks to you for keeping this software updated!

**Comment by Minoru** [comment] 2018-08-18 09:49
Hi! That does sound like #115. Can you upgrade to 2.11 (at least), which includes the fix?

**Comment by MaryJo42** [comment] 2018-08-18 11:41
My bad, Youtube subscriptions don't work in 'newsbeuter' so not unexpected that they fail in 'newsboat'. 
Subscription podcast that fails in newsboat does not fail in newsbeuter however.
Example:  https://s3-eu-west-1.amazonaws.com/taw-player-audio/WEEKENDERTAW160818.m4a - leads to 'invalid url'
Updated to latest git.

**Comment by Minoru** [comment] 2018-08-18 11:52
Okay, can you provide URLs so I can test this?

If the URLs are private, can you at least post excerpts with `<enclosure>` or `<link rel="enclosure">` tags? You can change the URLs in them, I don't need to fetch the files.

The m4a file has a MIME of audio/x-m4a, which should work in 2.11 and later, unless the feed specifies some other MIME which Newsboat won't accept. I really need to see the feed to tell what's going on.

**Comment by MaryJo42** [comment] 2018-08-18 12:28
https://username:password@www.theanfieldwrap.com/player/subscribe
This is the feed in question

**Comment by Minoru** [comment] 2018-08-18 12:37
I don't need the files, I need the feed. I can't access the one you linked because I don't have the credentials. Again—can you fetch it with CURL or Wget and post the `<enclosure>` or `<link rel="enclosure">` tags? I need to see what type they specify for the podcasts.

**Comment by Minoru** [comment] 2018-08-18 13:25
Oh, cool! And this fails with 2.11? Are you totally sure you're running the correct version? Newsboat should accept any type that starts with "audio/", so this podcast should work fine.

**Comment by MaryJo42** [comment] 2018-08-18 13:34
Yes, this fails latest git - newsboat r2.12-83-g54ce - 'invalid url'.
But everything else works well now so I'll close this issue.
Thanks again for your time!

**Comment by fmilani** [comment] 2021-08-22 20:35
Hi!. I'm having the same issue (Invalid URL: '') when enqueing a podcast to download.

I'm on version 2.24.0 of newsboat.
This is the rss feed url: https://changelog.com/jsparty/feed

Each item on the feed has a enclosure tag with type audio. e.g.: 
`<enclosure url="https://cdn.changelog.com/uploads/jsparty/189/js-party-189.mp3" length="76386981" type="audio/mpeg"/>`

**Comment by Minoru** [comment] 2021-08-22 22:19
Hmm, I can't reproduce this on current `master` (17dd). The newest item ("Automate all the things with Node.js") enqueued just fine.

@fmilani, when you open this item, do you see a line in the header that says:

```
Podcast Download URL: https://cdn.changelog.com/uploads/jsparty/189/js-party-189.mp3 (type: audio/mpeg)
```

Also, can you please show your config file?

**Comment by fmilani** [comment] 2021-08-22 22:58
This is what the header shows:

```
Newsboat 2.24.0 - Article 'Automate all the things with Node.js' (16 unread, 20 total)
Feed: JS Party: JavaScript, CSS, Web Development
Title: Automate all the things with Node.js
Author: Changelog Media
Date: Fri, 20 Aug 2021 13:30:00 -0300
Link: https://changelog.com/jsparty/189
```

This is my config file:
```
urls-source "inoreader"
inoreader-app-id "XXXXXXXXX"
inoreader-app-key "XXXXXXXXX"
inoreader-login "XXXXXXXXX"
inoreader-password "XXXXXXXXX"

color info default color8 bold
color listfocus default color8 bold
color listfocus_unread default color8 bold

auto-reload yes
reload-threads 100

bind-key j next
bind-key k prev
bind-key J next-feed
bind-key K prev-feed
bind-key j down article
bind-key k up article
bind-key J next article
bind-key K prev article
bind-key u toggle-show-read-feeds
bind-key l open
bind-key h quit
```
As you can see I connect newsboat to my inoreader account to get my feeds.

Thanks for the help!

**Comment by Minoru** [comment] 2021-08-22 23:43
Ah, that explains it: Inoreader simply doesn't show enclosures in its API.

The message is misleading though. I filed a separate issue about it: https://github.com/newsboat/newsboat/issues/1748

Thanks for reporting, and sorry this can't be fixed on Newsboat's side.

**Closed by Minoru** 2021-08-22 23:43 UTC
Labels: bug, cannot-reproduce

**Comment by fmilani** [comment] 2021-08-23 00:17
Got it! No problem! Thanks again for the fast responses!
