### ISSUE TITLE
All rss entries for a feed get deleted when performing a search when newsboat enters an invalid state

### ISSUE THREAD

**Issue by taiyu-len** [newsboat/newsboat#685] opened 2019-10-20 02:38 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
newsboat 2.17.1 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2019 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2019 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json

newsboat 2.17.1
System: Linux 5.3.5-arch1-1-ARCH (x86_64)
Compiler: g++ 9.1.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.66.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.8.2 nghttp2/1.39.2 (compiled with 7.66.0)
SQLite: 3.30.1 (compiled with 3.29.0)
libxml2: compiled with 2.9.9
```

Steps to reproduce the issue:
1. Open rss feed with an unread entry (A) and another entry (B)
2. Search so that only entry (B) is shown.
4. Press enter to open entry (B)
5. Press n or p to move to entry (A) which is not in search results.
6. Press q to go back. *newsboat enters invalid state here.*
7. Perform another search which always fails. *causes entries to get deleted here*
8. Press q until program closes.
9. All entries from that rss feed are now deleted.

**Other info you think is relevant**:

Normally, searching, opening a result, then quitting will bring you back to the search results.
however, by moving to an unread entry first and then quitting, it goes to an invalid state where all entries are shown.
making a search while in that invalid state then causes the database lose all entries for that feed.

quitting again will show that the url for the feed has been set to `search:`, and doing other things like `mark-feed-read` causes the program to freeze.

**Comment by Minoru** [comment] 2019-10-20 17:47
Reproduced with f27408b56446aefe473eff60fe66580fbe200050. Thank you for the report!

**Comment by mbwgh** [comment] 2020-07-01 12:55
I just got hit hard by this, lost about 4k entries.
Is there a way to make the DB immutable (except for adding new entries of course)?

**Comment by Minoru** [comment] 2020-07-01 13:00
@mbwgh Ouch, sorry to hear that! No, there is no way to make it immutable, and very little point—how would you e.g. mark items read? The best strategy against this kind of bugs is to make backups regularly.

**Comment by dennisschagt** [comment] 2020-07-01 14:12
From some previous debugging, it looks like the items are removed when the cache is cleaned up (happens when Newsboat is closed).
It looks like this issue does not result in loss of data when the setting [`cleanup-on-quit`](https://newsboat.org/releases/2.20/docs/newsboat.html#cleanup-on-quit) is set to `no`.

**Comment by dennisschagt** [comment] 2020-07-01 19:58
It looks like this issue is the result of several combined behaviors of Newsboat.

Taking the provided reproduction steps as guidance:

| # | Step | Remarks  |
|---|---|---|
| 1 | Open rss feed with an unread entry (A) and another entry (B) | - |
| 2 | Search so that only entry (B) is shown. | This creates a new ItemListFormAction with a dummy feed populated with the searchresults (expected behavior) |
| 3 | Press enter to open entry (B) | - |
| 4 | Press n or p to move to entry (A) which is not in search results. | First looks through the itemlist with searchresults but doesn't find any unread items. Then, Newsboat searches for unread items in regular (non-search) feeds. If found, it updates the `feed` variable in the search instance of `ItemListFormAction` ([1](https://github.com/newsboat/newsboat/blob/beec069192b7144fced544c5502d210b45aed634/src/itemviewformaction.cpp#L343) [2](https://github.com/newsboat/newsboat/blob/beec069192b7144fced544c5502d210b45aed634/src/view.cpp#L799) [3](https://github.com/newsboat/newsboat/blob/beec069192b7144fced544c5502d210b45aed634/src/itemlistformaction.cpp#L1412)) |
| 5 | Press q to go back. newsboat enters invalid state here. | The search `ItemListFormAction` instance now shows all items of the feed which it switched to in step 4 |
| 6 | Perform another search which always fails | This search action reuses the existing (current) `ItemListFormAction` instance because it is marked as a list of search results (`show_searchresult == true`). This causes it to overwrite the rssurl with a hardcoded string: `"search:"` ([1](https://github.com/newsboat/newsboat/blob/beec069192b7144fced544c5502d210b45aed634/src/itemlistformaction.cpp#L879)) (applied to the regular feed which was set in step 4). |
| 7 | Press q until program closes. | On exit, Newsboat removes all feeds and items which `rssurl` is no longer in the list of feeds. As the feed configured in step 4 does not have its original rssurl configured anymore, items related to it are removed from the cache ([1](https://github.com/newsboat/newsboat/blob/beec069192b7144fced544c5502d210b45aed634/src/controller.cpp#L498) [2](https://github.com/newsboat/newsboat/blob/beec069192b7144fced544c5502d210b45aed634/src/cache.cpp#L757) [3](https://github.com/newsboat/newsboat/blob/beec069192b7144fced544c5502d210b45aed634/src/cache.cpp#L761-L777)) |

The first unexpected behavior is in step 4.
Possible solution: Disallow switching to a different feed from within article lists and article views related to a search query.

It might make sense to split the implementation for regular article lists and the search results lists (might introduce a bit of duplication but I expect it significantly reduces the complexity of the `ItemListFormAction`).

@taiyu-len: Thanks for providing these clear steps to reproduce.

**Comment by Minoru** [comment] 2020-07-05 20:13
@dennisschagt, thanks for investigating! :+1:

> Possible solution: Disallow switching to a different feed from within article lists and article views related to a search query.

I don't have better ideas.

> It might make sense to split the implementation for regular article lists and the search results lists

Yeah, I guess a new `SearchResultsListFormAction` (gosh…) can inherit from `ItemListFormAction`, block some operations in `process_operation`, and delegate everything else to the base class. Basically, it should disable all the ways to exit it other than `quit`.

I'm not too happy solving this through inheritance, since it complicates porting to Rust, but we already have that going on in this part of the code, so I don't think it makes things any worse.

**Comment by dennisschagt** [comment] 2020-12-21 14:50
I'm working on some refactoring/fixing related to search results, however, I can no longer reproduce this issue.
It looks like this issue got fixed by https://github.com/newsboat/newsboat/commit/395617b46c5235a2062d305cc1353f40dbbf4668 (https://github.com/newsboat/newsboat/pull/1091).

**Closed** 2020-12-24 12:04 UTC
Labels: bug
