### ISSUE TITLE
Werror=stack-protector  TagSoupPullParser::decode_entity(std::string s)

### ISSUE THREAD

**Issue by cubajashi** [newsboat/newsboat#1598] opened 2021-04-18 21:52 UTC
Try to build 2.23 with `-fstack-protector-all -Wstack-protector`

```
g++ -std=c++11 -O2 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Itarget/cxxbridge/libnewsboat-ffi/src/ -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR='"/usr/share/locale"' -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -DHAVE_OPENSSL=1 -march=native -O2 -pipe -fno-plt -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wstack-protector --param ssp-buffer-size=4 -o src/tagsouppullparser.o -c src/tagsouppullparser.cpp
src/tagsouppullparser.cpp: In member function 'std::string newsboat::TagSoupPullParser::decode_entity(std::string)':
src/tagsouppullparser.cpp:443:13: error: stack protector not protecting local variables: variable length buffer [-Werror=stack-protector]
  443 | std::string TagSoupPullParser::decode_entity(std::string s)
      |             ^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [Makefile:176: src/tagsouppullparser.o] Error 1
```

**Comment by Minoru** [comment] 2021-04-18 22:18
Well, that's okay — it's just a warning that the stack protector won't work for this particular function. It's caused by these two arrays:

- https://github.com/newsboat/newsboat/blob/dc3757aae9aa78323465caa5dc74f29325e0ab3f/src/tagsouppullparser.cpp#L451
- https://github.com/newsboat/newsboat/blob/dc3757aae9aa78323465caa5dc74f29325e0ab3f/src/tagsouppullparser.cpp#L508

It's innocuous, but I think we can avoid the warning if we use `MB_LEN_MAX` instead of `MB_CUR_MAX`. I'm looking into that.

**Comment by Minoru** [comment] 2021-04-19 19:58
This is now fixed in the `master` branch, and will be released in 2.24. Thank you for the report, @cubajashi!

**Closed** 2021-04-19 19:58 UTC
Labels: enhancement

**Comment by cubajashi** [comment] 2021-04-20 22:45
Thank you for the fix @Minoru.

From a "simple user" perspective as i am, it's weird to notice that a simple compiler flag didn't used in the past by anyone who ever tryd to build newsboat.

**Comment by Minoru** [comment] 2021-04-21 12:10
Compilers have a ton of flags, I'm not surprised that some of them are missed by the end users :)

Come to think of it, we already use `-fstack-protector-strong` in CI, but don't pass `-Wstack-protector`. I should've added it to, to avoid regressing on this issue. Will do so in a moment!
