### ISSUE TITLE
[bug] Whitespace between line breaks in <title> is not collapsed properly

### ISSUE THREAD

**Issue by herrsimon** [newsboat/newsboat#1312] opened 2020-11-24 21:04 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: 2.21.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):  

```
exec:/tmp/testfeed.sh
```

Whitespace appearing between line breaks in <title> node is not collapsed properly
Steps to reproduce the issue:

Make /tmp/testfeed.sh output a feed with an entry containing a linebreak followed by some spaces in the <title> node. Example output: 

```
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <link href="https://www.newsboat.org" rel="self" type="application/atom+xml"/>
  <title type="html">Testfeed</title>
  <id>sV2vcY6tU6Y</id>
  <updated>2020-11-24T00:00:00-05:00</updated>
   <entry>
    <id>aoeusnthdai</id>
    <updated>2020-11-23T18:25:34Z</updated>
    <published>2020-08-18T18:13:49Z</published>
    <title>Some long title with a line break 
  followed by three spaces, which are not collapsed to one<title>
    <summary>Summary
</summary>
    <author>
      <name>Jon Doe</name>
    </author>
      <link href="https://www.newsboat.org" rel="alternate" type="text/html"/>
 </entry>
</feed>
```

**Comment by Minoru** [comment] 2020-11-24 22:17
This is a duplicate of #1227, which is already fixed and will be released as part of Newsboat 2.22 at the end of December. Thanks for an easily reproducible bug report, though!

Note that the example output you provided doesn't contain a closing \<title> tag, and so Newsboat includes "Summary" and "Jon Doe" into the item title. If I'm reading [RFC 4287](https://tools.ietf.org/html/rfc4287) correctly, this behaviour is acceptable: [§4.2.14](https://tools.ietf.org/html/rfc4287#section-4.2.14) says that `atom:title` is a Text construct, which according to [§3.1](https://tools.ietf.org/html/rfc4287#section-3.1) can contain plain text or (X)HTML. [§3.1.1](https://tools.ietf.org/html/rfc4287#section-3.1.1) explains that the default is plain text, but also requires that plain text shouldn't contain child XML nodes. So the input is malformed, and Newsboat is doing an okay job (IMHO) processing it.

Since the bug itself is fixed, I'm closing this issue. If you'd like to argue about the Atom spec, please open an issue specifically for that ;)

**Closed by Minoru** 2020-11-24 22:17 UTC

**Comment by herrsimon** [comment] 2020-11-24 23:07
Great, thanks a lot! Just started using newsboat but it's already clear that I made the right choice with a community that knowledgeable and fast to respond!

PS: No arguing about the Atom spec, but probably about a missing slash in my sample output...

**Comment by Minoru** [comment] 2020-11-24 23:11
> Great, thanks a lot! Just started using newsboat but it's already clear that I made the right choice with a community that knowledgeable and fast to respond!

Hey, welcome aboard! :) Let's see if you change your mind once you've run into more serious bugs that we weren't able to fix yet. :P
