### ISSUE TITLE
Regression: `open-in-browser` redraws the article list

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1292] opened 2020-11-15 10:39 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: r2.21-175-g3bee9

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
mark-as-read-on-hover yes
show-read-articles no
browser firefox
```

Steps to reproduce the issue:

1. start Firefox (to avoid Newsboat blocking);

1. open a feed with four unread items (or more, but adjust the numbers below, then);

2. move to the second item. (Note: both the first and the second items are now marked read because of `mark-as-read-on-hover`);

3. press `o` to open the second item in Firefox.

**Expected behaviour**: Newsboat's screen quickly flashes while Firefox command runs, and then I'm back to the article list with two read items and two unread items. The cursor is on the second one.

**Actual behaviour**: the screen flashes, and then I'm back to the article list with just two items — the ones that were on the third and fourth positions before. The cursor is now on the second (i.e. last) item, and it's marked read.

**Other info you think is relevant**:
I bisected this to 9aa2e7e5edfb14d38b7a1cb9d8799edadcddb5be, but haven't investigated who exactly redraws the list.

Note that the new behaviour is actually in alignment with how `show-read-feeds no` always behaved. This makes this issue a very interesting one: should Newsboat be consistent (both settings have similar effects), or should it be more useable (I find the new behaviour of `show-read-articles` disorienting).

**Comment by dennisschagt** [comment] 2020-11-15 11:07
> I bisected this to 9aa2e7e, but haven't investigated who exactly redraws the list.

I'm pretty sure the redraw is caused by the `set_redraw(true)` call near the end of `pop_current_formaction()`.
It wasn't hit before because we pushed a `nullptr` on the FormAction stack, causing `f == nullptr` to be true:
https://github.com/newsboat/newsboat/blob/3bee937fe8ea0de48a0b166107c720f0f0a6be67/src/view.cpp#L926-L964

This made me aware of another problem. With the provided configuration, messages are also marked as read when resizing the terminal.
Yet another problem, maybe (not yet tested), is that any error message from `open_in_browser()` might get overwritten by the `f->get_form().set("msg", "");` call.

I think the issue is that `do_redraw(true)` is used for two separate reasons:
- Redrawing the form (after a ^L press or after a terminal resize)
- Updating the items which should be shown

It might make sense to introduce a `do_update()` option next to the `do_redraw()` option.

**Comment by dennisschagt** [comment] 2020-11-15 11:15
> Yet another problem, maybe (not yet tested), is that any error message from open_in_browser() might get overwritten by the f->get_form().set("msg", ""); call.

Never mind, error messages from a failing call to `open_in_browser()` are set after it returns, e.g.:
https://github.com/newsboat/newsboat/blob/4fa0572e0b589d8b7e7b93da6eca4fb91ee4ed8f/src/itemlistformaction.cpp#L138-L145

**Comment by Minoru** [comment] 2020-11-15 12:39
> This made me aware of another problem. With the provided configuration, messages are also marked as read when resizing the terminal.

Yep :(

I agree that `do_redraw` serves two purposes, and should be split. `invalidate()` in itemlist kind of tries to do something similar, but it turns into a full redraw after `invalidate_everything()`.

Would you work on this? Since it's a regression, it better be fixed before the release. If not, I can revert the PR that introduced it, and then the deadline moves from "2.22" to "whenever".

**Comment by dennisschagt** [comment] 2020-11-15 13:26
> Would you work on this?

I expect to have time for this next week.

> Since it's a regression, it better be fixed before the release.

Agreed, so I added it to the `2.22` milestone.

**Closed** 2020-11-19 20:16 UTC
Labels: bug
