### ISSUE TITLE
Problem with Arabic Langauge

### ISSUE THREAD

**Issue by knassar702** [newsboat/newsboat#1696] opened 2021-07-04 19:42 UTC
In short newsboat reads Arabic words in a random manner

example
--
 `النظام التعليمي مكسور...ولازم يتصلح` 

newsboat will reads this words randomly
![abo](https://user-images.githubusercontent.com/45688522/124397210-eec37680-dd0e-11eb-8cf2-34644a46cb5c.png)

like this in english
`hello my name is khaled`
`khaled name my is hello`

#### env info
* Newsboat version : 2.24.0
* OS : Void Linux (glibc)
* Terminal: Terminator/kitty 

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):
```
#show-read-feeds no
auto-reload yes

external-url-viewer "urlscan -dc -r 'linkhandler {}'"

bind-key j down
bind-key k up
bind-key j next articlelist
bind-key k prev articlelist
bind-key J next-feed articlelist
bind-key K prev-feed articlelist
bind-key G end
bind-key g home
bind-key d pagedown
bind-key u pageup
bind-key l open
bind-key h quit
bind-key a toggle-article-read
bind-key n next-unread
bind-key N prev-unread
bind-key D pb-download
bind-key U show-urls
bind-key x pb-delete

color listnormal cyan default
color listfocus black yellow standout bold
color listnormal_unread blue default
color listfocus_unread yellow default bold
color info red black bold
color article white default bold

browser linkhandler
macro , open-in-browser
macro t set browser "firefox" ; open-in-browser ; set browser linkhandler
macro a set browser "tsp youtube-dl --add-metadata -xic -f bestaudio/best" ; open-in-browser ; set browser linkhandler
macro v set browser "setsid -f mpv" ; open-in-browser ; set browser linkhandler
macro w set browser "firefox" ; open-in-browser ; set browser linkhandler
macro d set browser "dmenuhandler" ; open-in-browser ; set browser linkhandler
macro c set browser "echo %u | xclip -r -sel c" ; open-in-browser ; set browser linkhandler
macro C set browser "youtube-viewer --comments=%u" ; open-in-browser ; set browser linkhandler
macro p set browser "peertubetorrent %u 480" ; open-in-browser ; set browser linkhandler
macro P set browser "peertubetorrent %u 1080" ; open-in-browser ; set browser linkhandler

highlight all "---.*---" yellow
highlight feedlist ".*(0/0))" black
highlight article "(^Feed:.*|^Title:.*|^Author:.*)" cyan default bold
highlight article "(^Link:.*|^Date:.*)" default default
highlight article "https?://[^ ]+" green default
highlight article "^(Title):.*$" blue default
highlight article "\\[[0-9][0-9]*\\]" magenta default bold
highlight article "\\[image\\ [0-9]+\\]" green default bold
highlight article "\\[embedded flash: [0-9][0-9]*\\]" green default bold
highlight article ":.*\\(link\\)$" cyan default
highlight article ":.*\\(image\\)$" blue default
highlight article ":.*\\(embedded flash\\)$" magenta default
```

Steps to reproduce the issue:

1. put any Arabian youtube channel in your `urls` file (eg: https://www.youtube.com/channel/UCdttmnJddGQZsXRL_DbqgWA)

**Comment by Minoru** [comment] 2021-07-05 11:47
Thanks for the report! This is a duplicate of #481 though, so I'll close this one.

The core issue is still the same: YouTube's feed (which is at https://www.youtube.com/feeds/videos.xml?channel_id=UCdttmnJddGQZsXRL_DbqgWA BTW) doesn't have `lang` attribute, so Newsboat simply doesn't know that it's in Arabic. Sadly I still haven't found time to look into suggestions that were made in #481; help would be appreciated!

**Closed by Minoru** 2021-07-05 11:47 UTC
