### ISSUE TITLE
Wrong encoding in master branch when fetching feeds

### ISSUE THREAD

**Issue by amalgame21** [newsboat/newsboat#2251] opened 2022-11-09 18:51 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:m

git version of newsboat (installed by paru -S newsboat-git in arch linux)

Steps to reproduce the issue:

1. Upgrade to git version of newsboat from version 2.29.0

2. Run `newsboat -x reload`

3. Run `newsboat`, the feeds are wrongly encoded

![newsboat-trim](https://user-images.githubusercontent.com/93383215/200913299-f3a78e34-2721-4d23-ae45-83b2bd4ce7a9.jpg)

The feeds starting from Nov 9, 16:47 was fetched by git version of newsboat, before that was fetched by version 2.29.0.

Affected urls file entry is:
```
https://rthk.hk/rthk/news/rss/c_expressnews_clocal.xml
```

**Other info you think is relevant**:

Maybe relevant to #2230

**Comment by dennisschagt** [comment] 2022-11-09 20:30
> Maybe relevant to https://github.com/newsboat/newsboat/issues/2230

You are right, it is indeed very similar.
`https://rthk.hk/rthk/news/rss/c_expressnews_clocal.xml` also returns an HTTP 301 code (pointing to `http://rthk9.rthk.hk/rthk/news/rss/c_expressnews_clocal.xml`)
This isn't handled correctly in newsboat due to a recent change I made.

I reproduced your issue and verified that it will also be fixed by https://github.com/newsboat/newsboat/pull/2243

**Comment by amalgame21** [comment] 2022-11-09 23:55
Nice to see you have already found the cause of the problem and fixed it!

**Closed** 2022-11-12 15:18 UTC
