### ISSUE TITLE
Persistent article-list filters

### ISSUE THREAD

**Issue by ghost** [newsboat/newsboat#24] opened 2017-10-20 01:44 UTC
Filters are one of the great features of newsboat, however they only apply to the current article-list. For example, if I filter an article-list to only display items from today, the filter is cleared when I move on to the next article-list. It would be helpful if these filters could be set once and persist as I browse different article-lists, only resetting when I clear the filter manually. In my use case, this would allow me to eliminate certain query feeds based on date.

**Comment by diskotechjam** [comment] 2018-02-08 22:20
I was thinking about it today and it would be nice if the select filter dialogue worked the same as the select tag dialogue. For the select tag dialogue, you limit the feeds, enter a feed, and quit a feed without clearing the tag, but in the select filter dialogue, you limit the feeds, enter the feed, but when you quit the feed, it clears the filter.

**Comment by dennisschagt** [comment] 2020-05-26 15:24
The issue in [the 2nd comment](https://github.com/newsboat/newsboat/issues/24#issuecomment-364268289) got fixed in https://github.com/newsboat/newsboat/commit/8190ff7a810dfaada0b98b3f625154a86ace76b8 (PR https://github.com/newsboat/newsboat/pull/615) and is a duplicate of https://github.com/newsboat/newsboat/issues/227.

**Comment by dennisschagt** [comment] 2020-05-26 15:51
Quitting an article list and opening another still resets the filter.

However, when switching between article lists with operations like `next-feed` and `prev-feed` no longer resets the filter (implemented by [the same commit](https://github.com/newsboat/newsboat/commit/8190ff7a810dfaada0b98b3f625154a86ace76b8)).

I think the current behaviour is fine so this issue can probably be closed. Especially since the issue'author's account has been removed from Github.

**Comment by Minoru** [comment] 2020-05-26 15:58
I concur. Thanks for digging into this!

**Closed by Minoru** 2020-05-26 15:58 UTC
Labels: bug
