### ISSUE TITLE
query feeds show read/total article count of zero until opened (bug?)

### ISSUE THREAD

**Issue by herrsimon** [newsboat/newsboat#1408] opened 2021-01-07 19:32 UTC
Hello,

I just noticed that when starting up newsboat, query feeds always show a count of zero for new and total articles. After opening the feed once, the counts are displayed accurately. It would be nice if the counts would be accurate before opening the feed, this way it would also be possible to only show the query if there are unread articles present.

If it depends on the query: I have simply tagged several (real) feeds with a tag and the query feed in question searches for feeds with this tag.

**Comment by Minoru** [comment] 2021-01-07 19:46
> If you want query feeds to be updated at startup, set prepopulate-query-feeds to yes.

https://newsboat.org/releases/2.22/docs/newsboat.html#_query_feeds ;)

I guess that addresses this issue (and confirms it's not a bug), so I'm closing it.

**Closed by Minoru** 2021-01-07 19:46 UTC

**Comment by herrsimon** [comment] 2021-01-07 20:03
Ouch! Somebody should have read the manual properly before complaining... Thanks for the hint!
