### ISSUE TITLE
Time out when loading Articles from nextcloud

### ISSUE THREAD

**Issue by alhassanaraouf** [newsboat/newsboat#1223] opened 2020-10-09 15:01 UTC
Newsboat load urls from nextcloud news instanse but don't load the articles except starred ones

**Newsboat version**:
newsboat v20200917-1109-g0546b
System: Linux 5.8.14-0-edge (x86_64)
Compiler: g++ 10.2.0
ncurses: ncurses 6.2.20201003 (compiled with 6.2)
libcurl: libcurl/7.72.0 OpenSSL/1.1.1h zlib/1.2.11 brotli/1.0.9 nghttp2/1.41.0 (compiled with 7.72.0)
SQLite: 3.33.0 (compiled with 3.33.0)
libxml2: compiled with 2.9.10

**Config file**:
```
urls-source "ocnews"
ocnews-url "https://cloud.disroot.org"
 
ocnews-login "alhassanaraouf"
ocnews-passwordeval "~/scripts/get-pass.sh web/cloud.disroot.org"
 
ocnews-flag-star "s"
 
download-path "~/Downloads/Podcasts"
player "mpv"
```

**Other info you think is relevant**:
[newsboat log.txt](https://github.com/newsboat/newsboat/files/5355903/newsboat.log.txt)

**Comment by Minoru** [comment] 2020-10-09 15:23
Thank you for the report! Pastebins have a tendency to expire, so I'll copy the contents over here.

One detail that was mentioned on IRC but not here: this is Newsboa from edge repos of Alpine Linux, but you also experienced this on Arch Linux a month ago (with unknown version).

**Comment by alhassanaraouf** [comment] 2020-10-09 15:49
yes the problem happend to me with newsboat in alpine and arch repos but both with same nextcloud instance,

actually i will try testing it with other nextcloud instance today and report back

**Comment by Minoru** [comment] 2020-10-09 15:55
In the meantime I verified that "v20200917-1109-g0546b" corresponds to a build from this commit: https://git.alpinelinux.org/aports/commit/?id=0546b768ff4e1b48b085635a211854d4f9ff69f4 Should be equivalent to Newsboat 2.21.

**Comment by alhassanaraouf** [comment] 2020-10-10 00:35
I just installed new Nextcloud instance on AWS for testing and everything worked fine it was even faster in loading urls and reloading feeds

so i think the problem with the instance i use, i will contact the provider and try fixing the problem

**Comment by dennisschagt** [comment] 2020-12-02 09:31
Closing this as it seems to be an issue with the specific Nextcloud instance.

Feel free to reopen if you have any reason to believe this is caused by Newsboat.

**Closed by dennisschagt** 2020-12-02 09:31 UTC
Labels: bug, to check
