### ISSUE TITLE
2.30 fails to build

### ISSUE THREAD

**Issue by hyder365** [newsboat/newsboat#2297] opened 2022-12-25 18:26 UTC
Compiling 2.30 on the latest Arch Linux gives the following error:

g++ -std=c++11 -O2 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -I/build/newsboat/src/newsboat-2.30/target/cxxbridge/ -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR='"/usr/share/locale"' -I/usr/include/libxml2  -I/usr/include/json-c  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -DHAVE_OPENSSL=1 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -MD -MP -MF .deps/src/poddlthread.cpp -o src/poddlthread.o -c src/poddlthread.cpp
In file included from src/poddlthread.cpp:5:
src/poddlthread.cpp: In member function ‘void podboat::PodDlThread::run()’:
src/poddlthread.cpp:65:31: error: ‘CURLOPT_PROGRESSFUNCTION’ is deprecated: since 7.32.0. Use CURLOPT_XFERINFOFUNCTION [-Werror=deprecated-declarations]
   65 |                 handle.ptr(), CURLOPT_PROGRESSFUNCTION, progress_callback);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/curl/curl.h:1295:3: note: declared here
 1295 |   CURLOPTDEPRECATED(CURLOPT_PROGRESSFUNCTION, CURLOPTTYPE_FUNCTIONPOINT, 56,
      |   ^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [Makefile:175: src/poddlthread.o] Error 1

**Comment by Minoru** [comment] 2022-12-26 15:46
Thank you for the report! Turns out these warnings were only added in curl 7.87, which was released 5 days ago. That explains why our own CI didn't catch it; we're using Ubuntu which didn't pull in this update yet.

The problem is fixed by #2298 (thanks @dennisschagt!) I'll make a patch release sometime closer to the New Year. Meanwhile, one can temporarily disable the warning with `-DCURL_DISABLE_DEPRECATION` (https://github.com/curl/curl/pull/9667/files#diff-0652ea075ff6ddc585b01d147f439c0143706e9f2be1141a70281e08302d8171R40)

**Closed** 2022-12-26 15:47 UTC
