### ISSUE TITLE
Filter a single feed for a specific title

### ISSUE THREAD

**Issue by msilletti** [newsboat/newsboat#1167] opened 2020-09-02 11:05 UTC
I want use lkml rss feed to monitor all replies containing a specific title but after reading through [5.7 Query feeds](https://newsboat.org/releases/2.12/docs/newsboat.html#_query_feeds) in the docs I can't understand it. What should the correct syntax be to only show posts containing the title "Linux 5.9-rc3" from the rss?

I tried
```
https://lkml.org/rss.php "lkml"
"query:only interest:tags =~ \"lkml\" and ( title =~ \"Linux 5.9-rc3\" )" "lkml"
```

That gave all entries for lkml.org and none for what I want to see. I only want to see the filtered results and not the main lkml feed.

**Comment by Minoru** [comment] 2020-09-02 17:43
Your query looks fine to me, but I can't confirm that it works because:

1. the feed no longer contains any items with "Linux 5-9-rc3" in the title;
2. a query `"query:only interest:tags =~ \"lkml\" and ( title =~ \"media: vivid: \" )" "lkml"` shows 7 items both on current master (https://github.com/newsboat/newsboat/commit/e0e76c34bf3713a9e3c94d97c388120c31ad76b3) and 2.12 release.

Can you try my query and tell me what results you get?

Also, can you tell me what Newsboat version you're running, and show your config file? I guessed 2.12 because of the docs link, but really, you should have just filled out the issue template, which asks for that info.

**Comment by Minoru** [comment] 2020-09-02 19:48
@msilletti, note that colons inside double quotes might not work. I fixed that in #1170, but if you're running an earlier version, you might need to rephrase your filter expression to avoid that.

**Comment by msilletti** [comment] 2020-09-02 20:35
@Minoru - I built it from your master branch today so it is current. I did your suggestion and it works.
```
https://lkml.org/rss.php "lkml"
"query:only interest:tags =~ \"lkml\" and ( title =~ \"arm64\" )" "lkml"
```
Is there a syntax to combine the two lines into 1 line? The effect is I get a feed for the entire lkml.org and my filter. I don't want to see the entire lkml.org if this is possible?
```
   1 N   (101/101) lkml.org
   2 N       (3/3) only interest
```
Many thanks to you!

**Comment by dennisschagt** [comment] 2020-09-02 21:00
You might be able to hide the first feed by adding [a "hiding tag"](https://newsboat.org/releases/2.20.1/docs/newsboat.html#_tagging) (e.g. adding "!" as a tag to the end of the lkml.org line).
```
https://lkml.org/rss.php "lkml" "!"
"query:only interest:tags =~ \"lkml\" and ( title =~ \"arm64\" )" "lkml"
```

A few things to note:
- By hiding the feed, you cannot access it so you can only reload it by pressing `R` (= `reload-all`)
- The `!` tag might show up in the `selecttag` dialog (related to https://github.com/newsboat/newsboat/issues/500)

**Comment by Minoru** [comment] 2020-09-05 18:01
Since the bug is not reproducible with current version of Newsboat, and the other question is answered, I'm closing this.

**Closed by Minoru** 2020-09-05 18:01 UTC
Labels: bug, cannot-reproduce
