### ISSUE TITLE
Podboat : When the title of an episode contains `/`, it should not add a folder

### ISSUE THREAD

**Issue by edi9999** [newsboat/newsboat#1083] opened 2020-07-11 09:02 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

```
newsboat 2.20.1 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2020 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2020 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

newsboat 2.20.1
System: Linux 4.15.0-109-generic (x86_64)
Compiler: g++ 7.5.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.58.0 GnuTLS/3.5.18 zlib/1.2.11 libidn2/2.3.0 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3 (compiled with 7.58.0)
SQLite: 3.22.0 (compiled with 3.22.0)
libxml2: compiled with 2.9.10
```

Steps to reproduce the issue:

1. For the following RSS podcast : https://rss.acast.com/les-couilles-sur-la-table

2. One of the title of the podcasts is : `Nourrir son homme : le bon steak et le joli morceau (2/2)`

3. When enqueuing that episode to podboat, then downloading it, it will create a folder called `Nourrir son homme : le bon steak et le joli morceau (2` and create the mp3 file inside that folder.

I think that this / should be escaped to avoid creating folders.

**Comment by Minoru** [comment] 2020-07-11 19:26
Thanks for the report, @edi9999, but this is a duplicate of #836. Please subscribe there to get a notification when it's fixed.

**Closed by Minoru** 2020-07-11 19:26 UTC
