### ISSUE TITLE
PubDates before Unix Epoch are Mutilated

### ISSUE THREAD

**Issue by veqqq** [newsboat/newsboat#2871] opened 2024-09-27 19:20 UTC
newsboat 2.21.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2020 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2020 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

newsboat 2.21.0
System: Linux 6.8.0-40-generic (x86_64)
Compiler: g++ 10.2.1 20201207
ncurses: ncurses 6.3.20211021 (compiled with 6.2)
libcurl: libcurl/7.81.0 GnuTLS/3.7.3 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.18 (compiled with 7.72.0)
SQLite: 3.37.2 (compiled with 3.34.0)
libxml2: compiled with 2.9.10

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
datetime-format "%Y-%m-%d %H:%M"
```

Steps to reproduce the issue:

1. feed: https://alexalejandre.com/index.xml

2. "Sophokles"' date: <pubDate>Tue, 14 Feb 1826 00:00:00 +0000</pubDate> turns into 2098-04-28 08:56.

This seems related to this issue: https://github.com/newsboat/newsboat/issues/762 I would be happy to contribute and fix it, but I see it's been around for a while. So I ask: Are there are blockers which keep this from being a straight forward solution? Or what must be done?

**Comment by dennisschagt** [comment] 2024-09-28 11:35
I can reproduce the issue.
Looks like this is caused by storing the number as a 32-bit unsigned number in the database, causing the negative numbers to wrap around.
I've created a fix in PR https://github.com/newsboat/newsboat/pull/2872.

We currently use `curl_getdate()` to convert from dates specified according to RFC 822 to a unix timestamp.
From [the curl docs](https://curl.se/libcurl/c/curl_getdate.html):
> On systems with 64-bit time_t: if the year is less than 1583, this function returns -1. (The Gregorian calendar was first introduced 1582 so no "real" dates in this way of doing dates existed before then.) 

That seems to be fine for this feed with the earliest date being 1603, just mentioning it here in case you have/find feeds with even earlier dates.

**Comment by dennisschagt** [comment] 2024-09-28 11:37
> This seems related to this issue: https://github.com/newsboat/newsboat/issues/762 I would be happy to contribute and fix it, but I see it's been around for a while. So I ask: Are there are blockers which keep this from being a straight forward solution? Or what must be done?

I cannot reproduce the other issue.
It could be that it got resolved by an update in curl's `curl_getdate()`

Either way, thanks for reporting this issue and looking for related issues!

**Closed** 2024-10-01 20:52 UTC
