### ISSUE TITLE
Delete all finished Podboat downloads with one single keystroke

### ISSUE THREAD

**Issue by programandala-net** [newsboat/newsboat#811] opened 2020-03-16 15:15 UTC
**Newsboat version 2.18.0**:

Not sure if this is a bug, a feature or a Spanish translation error, but anyway it's a suggestion:

In Poadboat, "Shift+P" doesn't delete the finished downloads from the list, as the help bar reads, but only those previously deleted pressing "Shift+D"... one by one.

I've read the similar issue [keybinding delete all](https://github.com/newsboat/newsboat/issues/73), and tried `bind-key X delete-all-articles poadbeuter` (by the way, **"poadboat" is not accepted by `bind-key` yet**) in the config file, just in case, but it does nothing.

If I recall clearly, old versions on Podbeuter (not the latest 2.9) deleted all finished downloads with a single keystroke.

**Comment by Minoru** [comment] 2020-03-18 22:16
Hi! Sorry for the delay.

> In Poadboat, "Shift+P" doesn't delete the finished downloads from the list, as the help bar reads, but only those previously deleted pressing "Shift+D"... one by one.

I couldn't reproduce this. One thing that might've tripped you up is that `pb-mark-as-finished` only works on *played* downloads; for unplayed ones, it does nothing. If that's not it, please provide a step-by-step instructions on what exact podcast to add to Newsboat, what exact episode to enqueue, and what keys to press in Podboat.

> I've read the similar issue keybinding delete all, and tried bind-key X delete-all-articles poadbeuter in the config file, just in case, but it does nothing.

Yeah, `delete-all-articles` only works in Newsboat, not Podboat. All Podboat operations start with `pb-`. `quit`, `hard-quit` and `help` are common between Newsboat and Podboat.

> by the way, "poadboat" is not accepted by bind-key yet

Oh wow! Looks like I didn't rename it during the fork! It's now been like that for two and a half years, and you're the first one who noticed :) Thanks, I'll fix that promptly.

> If I recall clearly, old versions on Podbeuter (not the latest 2.9) deleted all finished downloads with a single keystroke.

I read Newsbeuter's changelog all the way back to 2.4, but found nothing on this. Too tired to do a similar dive into a Git log right now.

**Comment by Minoru** [comment] 2020-03-26 10:15
@programandala-net, were my suggestions of any help?

**Comment by programandala-net** [comment] 2020-03-26 10:40
> @programandala-net, were my suggestions of any help?

Yes, thanks, but I'm still investigating and trying some configuration
options. There are some things I still don't understand. Please don't
close the issue yet. Sorry for the delay. I didn't have much time these
days. 

-- 
Marcos Cruz
http://programandala.net

**Comment by Minoru** [comment] 2020-03-26 11:10
Ah, okay. No worries ;) Just wanted to make sure you haven't gone missing. Once the original reporter is gone, it's impossible for us to debug issues we can't reproduce ourselves.

**Comment by programandala-net** [comment] 2020-04-09 16:06
> I couldn't reproduce this. One thing that might've tripped you up is that `pb-mark-as-finished` only works on _played_ downloads; for unplayed ones, it does nothing.

I think I see the problem. First: I never play the audios from Podboat, but always copy them to another device. Second: The expression "Purge finished and deleted downloads", which was translated literally into Spanish, seems misleading. Shouldn't it be better "Purge played or deleted downloads"?

Anyway, this instigated me to fork the repository in order to correct and complete the Spanish translations, which have many issues.

> I read Newsbeuter's changelog all the way back to 2.4, but found nothing on this. Too tired to do a similar dive into a Git log right now.

Thanks, don't worry. I remember I didn't had this problem years ago, but maybe the reason was I played the files directly, I'm not sure.

**Comment by Minoru** [comment] 2020-04-10 19:35
> The expression "Purge finished and deleted downloads", which was translated literally into Spanish, seems misleading.

Ah, now I see it too: you're reading "finished downloads" literally, i.e. "files that were downloaded completely". But in Podboat, such files are called "ready". "Finished" means files that were explicitly marked as finished by the user via `pb-mark-as-finished` (bound to <kbd>m</kbd> by default) (wow, this setting is absent from the HTML doc!)

Renaming the states would be a breaking change, because they're exposed through [the `S` attribute of `podlist-format`](https://newsboat.org/releases/2.18/docs/newsboat.html#podlist-format-S), but we can add a section to the doc explaining each state better. I'll file a separate issue about it.

Do you agree this issue can be closed in favour of the issue about better docs?

**Comment by programandala-net** [comment] 2020-04-10 19:55
> Ah, now I see it too: you're reading "finished downloads" literally,
> i.e. "files that were downloaded completely". But in Podboat, such
> files are called "ready". "Finished" means files that were explicitly
> marked as finished by the user via `pb-mark-as-finished` (bound to
> <kbd>m</kbd> by default)

That's it. I saw "ready" on the list, but supposed "finished" was a
traslation issue, not a different state. Maybe "played", "listened" or
even "disposable" would be clearer descriptions instead of "finished".

> we can add a section to the doc explaining each state better. I'll
> file a separate issue about it.

Yes, that would be helpful, and simpler than changing the current
states, translations and shortcuts.

> Do you agree this issue can be closed in favour of the issue about
> better docs?

Of course, thanks!

-- 
Marcos Cruz
http://programandala.net

**Comment by Minoru** [comment] 2020-04-10 20:25
Okay, closing in favour of #875 and #876 then. Thanks for the discussion!

**Comment by Minoru** [comment] 2020-04-10 20:25
Also re-labeling as "question" since this turned out not to be a bug.

**Closed by Minoru** 2020-04-10 20:25 UTC
Labels: bug, cannot-reproduce
