### ISSUE TITLE
Query feeds using "content" do not appear to work

### ISSUE THREAD

**Issue by jeremyf** [newsboat/newsboat#872] opened 2020-04-09 16:35 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: 2.19

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config): `n/a` (I have tested with no config)

In my `urls` file I have tested the following:

```
"query:Blogroll for Take on Rules:tags # \"blogroll\""
"query:Contains the (with include oper):content#\"the\""
"query:Contains the (with regexp):content=~\"the\""
```

I also have approximately ~550 feed subscriptions.

My home newsboat screen shows the following:

```
newsboat 2.19.0 - Your feeds (6 unread, 560 total)
   1         (0/0) Blogroll for Take on Rules
   2         (0/0) Contains the (with include oper)
   3         (0/0) Contains the (with regexp)
```

When I select select `1` feed, I open a list dialog and see posts in my blog roll. I go back to the feed list dialog and now see `(0/651)` for feed `1`. When I select feeds `2` and `3` I get `Error: feed contains no items!`.

I have also tried the above with a config that has `prepopulate-query-feeds yes`, which renders the following feed list:

```
newsboat 2.19.0 - Your feeds (6 unread, 561 total)
   1       (0/651) Blogroll for Take on Rules
   2         (0/0) Contains the (with include oper)
   3         (0/0) Contains the (with regexp)
```

**Other info you think is relevant**: This may have an interplay with #218.

**Comment by jeremyf** [comment] 2020-04-09 16:50
What I'm ultimately interested in is to query for content that includes a URL (takeonrules.com). However, I figured I'd go with a more general statement.

Note, I have tested the `#` and `=~` for other strings as well.

**Comment by Minoru** [comment] 2020-04-10 18:19
Thanks for the report! This is a duplicate of #111, so I'm closing this one. I admit I still haven't thought how to re-architecture things to avoid this bug.

**Closed by Minoru** 2020-04-10 18:19 UTC
