### ISSUE TITLE
Error with make requirements: cargo curl-sys

### ISSUE THREAD

**Issue by remi-garcia** [newsboat/newsboat#1902] opened 2021-12-11 09:17 UTC
```bash
$ make
cargo build --package libnewsboat-ffi --verbose --release
    Updating crates.io index
error: failed to select a version for the requirement `curl-sys = "=0.4.51"`
candidate versions found which didn't match: 0.4.45+curl-7.78.0, 0.4.44+curl-7.77.0, 0.4.43+curl-7.76.0, ...
location searched: crates.io index
required by package `libnewsboat v2.25.0 (/home/remi/software/newsboat/rust/libnewsboat)`
make: *** [Makefile:142: /home/remi/software/newsboat/target/release/libnewsboat.a] Error 101

$ cargo search curl-sys
curl-sys = "0.4.51+curl-7.80.0"    # Native bindings to the libcurl library
```

I've tried cargo clearing cache. cargo check, cargo update, cargo manythings, no success.

I had compiled `Newsboat r2.24-127-gd13b`:
```
Newsboat r2.24-127-gd13b
System: Linux 5.11.0-41-generic (x86_64)
Compiler: g++ 9.3.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3 (compiled with 7.68.0)
SQLite: 3.31.1 (compiled with 3.31.1)
libxml2: compiled with 2.9.10
```
and tried to update it this morning. I'm stuck and have no clue on how to pursue.

OS: Ubuntu 20.04.3
curl --version: curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 etc.

**Comment by Minoru** [comment] 2021-12-11 14:21
Thanks for the report! It looks like Cargo failed to update the index, even though it tried. (`cargo search` bypasses the local copy of an index and makes an HTTP query to crates.io.)

The only suggestion I have is to remove or rename _~/.cargo_ and run `make` again. This will make Cargo re-fetch the entire index; hopefully it'll succeed this time around.

It'd also be good to report this upstream, to https://github.com/rust-lang/cargo/ They might have more ideas on how to debug it.

It would also be useful to know what Cargo version you have, and how you installed (Ubuntu repos? Rustup?).

**Comment by Minoru** [comment] 2021-12-11 14:23
I also tried to reproduce it in a Docker container created from ubuntu:20.04 image. After `apt upgrade` and installing `cargo` and `rustc` from the repos, I couldn't reproduce. This was a new container, so it fetched the entire index as it is today.

We also have a CI job that caches the Cargo index, and it runs for every commit. I didn't see this error in CI, so at least *some* setups are not affected by this.

**Comment by remi-garcia** [comment] 2021-12-14 19:29
cargo --version: cargo 1.53.0
I have cargo from Ubuntu repos.

Renaming `~/.cargo` solved the problem.
I've compressed the old folder and I could upload it somewhere if you want. The size of the archive is around 500MB.

**Comment by Minoru** [comment] 2021-12-17 16:37
I encourage you to reprort this to https://github.com/rust-lang/cargo/. I'm not a Cargo developer, so "remove the cache and try again" is essentially the limit of my Cargo-debugging skill. Even if I saw the contents of ~/.cargo, I wouldn't know where to start debugging the cause of the Cargo error.

I'm glad you can compile Newsboat now, and I think this resolves the issue, so I'll close it.

**Closed by Minoru** 2021-12-17 16:37 UTC
Labels: bug, cannot-reproduce
