### ISSUE TITLE
Return to tag list when quitting a tag list item

### ISSUE THREAD

**Issue by Eucyon** [newsboat/newsboat#973] opened 2020-05-31 18:57 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
2.19.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):
N/a

Steps to reproduce the issue:
1. Go to the tag list (press "t").
2. Select one tag by pressing "enter". You'll get a list of the feeds with this tag.
3. Quit this view by pressing "q". The feed list is show.

I would have expected the tag list.

**Comment by Minoru** [comment] 2020-05-31 19:26
Sorry, but this is working as intended. If you're looking at certain info (say, a list of feeds), an action that returns the same kind of info (say, a list of feeds matching a tag) will just update the current dialog; if the info is of a different kind (say, it's a list of articles within a feed), a new dialog will be created.

I think your expectations differ from Newsboat's behaviour in just two aspects:
1. you can't return to the tag list by pressing "q";
2. tag list doesn't "remember" which tag you've selected last, so if you're going through tags one by one, you have to scroll through the tag list every time, instead of just moving one item down.

The first point is a "wontfix", but the second one I'd consider a bug. Would that help your use-case if the tag list put the cursor on the currently selected tag?

**Comment by Eucyon** [comment] 2020-06-01 05:20
For me, what I described is more intuitive. But I can live with the current situation.

Your suggestion to remember the cursor position of the tag list is not necessary for me.

Thanks anyway!

**Comment by Minoru** [comment] 2020-06-01 11:58
Okay, closing this then :heart:

**Closed by Minoru** 2020-06-01 11:58 UTC
Labels: bug, question, wontfix
