### ISSUE TITLE
Problems rendering the topmost line of an article

### ISSUE THREAD

**Issue by glacambre** [newsboat/newsboat#273] opened 2018-09-11 06:20 UTC
**Newsboat version (copy from `newsboat -v`)**:
```
newsboat 2.12.0
System: Linux 4.17.0-1-amd64 (x86_64)
Compiler: g++ 7.3.0
ncurses: ncurses 6.1.20180714 (compiled with 6.1)
libcurl: libcurl/7.61.0 GnuTLS/3.5.19 zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.4) libssh2/1.8.0 nghttp2/1.
32.0 librtmp/2.3 (compiled with 7.60.0)
SQLite: 3.24.0 (compiled with 3.24.0)
libxml2: compiled with 2.9.4
```
But can also reproduce on master.

Steps to reproduce the issue:

1. Add `https://jvns.ca/atom.xml "Julia Evans"` to your url file

2. Starts newsboat, go to the feed you just added, select the `Editing my blog's HTTP headers with Cloudflare workers` article.

3. Scroll down until the end of the article

You should see the topmost line be overwritten with another line from the article. What line is used to overwrite the topmost line seems to depend on the width of your terminal.

**Other info you think is relevant**:
I can reproduce this under urxvt, st and neovim's terminal.

**Comment by Minoru** [comment] 2018-09-11 18:33
Reproduced on 49df8768b95c9a6fb019b2e1169885b7ad39391f in Tmux inside URXVt.

Observed the same issue with "New zine: Bite Size Command Line!", "Batch editing files with ed", "How to get a core dump for a segfault on Linux", and "Reverse engineering the Notability file format".

Here's a copy of the feed in case I need it later: [atom.xml.gz](https://github.com/newsboat/newsboat/files/2372238/atom.xml.gz)

I suspect our HTML parser not escaping some input, which later makes STFL behave weirdly. Or maybe it's just really long lines that STFL has trouble wrapping.

@glacambre, thank you for the report!

**Comment by dennisschagt** [comment] 2020-03-19 22:25
It looks like this is the same bug in STFL which caused #506 (I could only reproduce after installing STFL 0.24 instead of my own patched version).

A patch for STFL is available at https://github.com/newsboat/newsboat/issues/506#issuecomment-596091556
As this bug is not caused by Newsboat, I will close this issue.

**Closed by dennisschagt** 2020-03-19 22:25 UTC
Labels: bug
