### ISSUE TITLE
Articles read with open-all-unread-in-browser-and-mark-read not being synced

### ISSUE THREAD

**Issue by aleprovencio** [newsboat/newsboat#1449] opened 2021-01-26 21:08 UTC
**Newsboat version: 2.22.1

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
feed-sort-order firsttag
show-keymap-hint no
show-read-feeds no

urls-source "ocnews"
ocnews-url ""
ocnews-login ""
ocnews-passwordeval ""
ocnews-flag-star "s"

unbind-key j
unbind-key k
bind-key j down
bind-key k up
bind-key ^D pagedown
bind-key ^U pageup
bind-key g home
bind-key G end
bind-key o open-in-browser-and-mark-read
bind-key h quit
bind-key l open
bind-key O open-all-unread-in-browser-and-mark-read
bind-key z toggle-show-read-feeds
bind-key m toggle-article-read
```

Steps to reproduce the issue:

1. acess the article list of a feed

2. on some unread items, use the operation `open-in-browser-and-mark-read` (mapped to `o` in my case)

3. on some unread items, use the operation `open-all-unread-in-browser-and-mark-read` (mapped to `O` in my case)

4. Despite all articles that were part of previous actions are marked as read on article list, only the ones read with `open-in-browser-and-mark-read` are synced as read.

**Other info you think is relevant**:
Maybe this is only an issue with `ocnews`?

**Comment by dennisschagt** [comment] 2021-01-26 23:28
I can reproduce, both on current master and on older versions of Newsboat (e.g. reproduced with r2.18).

> Maybe this is only an issue with ocnews?

From the code, it looks like this issue exists for all of the Newsboat remote APIs.

**Comment by Minoru** [comment] 2021-01-27 00:34
The fix is now merged. Thanks for the report, @aleprovencio!

**Closed** 2021-01-27 00:34 UTC
Labels: bug

**Comment by Minoru** [comment] 2021-10-15 16:39
Hmm. The only commit between 2.23 and 2.25 that touched ocnews API is 0f1d5b002bf414c36dc2ad9de89ca6fd98d47354, but if it's broken, it should have affected all operations of that API, not just mark-read. @dennisschagt, do you still run nextcloud, can you try and reproduce this?

**Comment by Minoru** [comment] 2021-10-16 12:21
Thanks! Works for me too.

The only cause I can think of is unstable network. We make HTTP requests on separate threads, and we never check if they succeeded or not (and we never retry). So if the network is slow or looses requests, Newsboat could fail to mark some items. But again, that should affect *everything*, not just `open-all-unread-in-browser-and-mark-read`.

@aleprovencio, do you have any other News clients that you can test from the same network? Do other operations work okay in Newsboat? I don't have a specific theory to test, just trying to find some more information to figure out what's going on.

**Comment by dennisschagt** [comment] 2021-10-18 20:51
@aleprovencio It might be possible to debug the issue by using Wireshark.
This might take some effort if HTTPS is used between Newsboat and the Nextcloud server.

Steps to create a Wireshark trace of the relevant traffic:
1. Run `touch /tmp/ssl-secrets.txt`
2. Start wireshark (GUI)
3. Configure SSL secrets file in Wireshark
    - Edit -> Preferences -> Protocols -> TLS
        - Enter filename in the "Master-Secret log filename" field: /tmp/ssl-secrets.txt 
4. Start recording traffic in Wireshark (select the relevant network interfaces; the "Any" interface might suffice)
5. Apply Wireshark display filter `(http || http2 || http3) && tcp.port == 443` (replace 443 with the port used by the Nextcloud server)
6. Start Newsboat with the SSLKEYLOGFILE environment variable:
    ```
    SSLKEYLOGFILE=/tmp/ssl-secrets.txt newsboat
    ```
7. In Newsboat, execute some `open-in-browser-and-mark-read` and `open-all-unread-in-browser-and-mark-read` commands
8. Check the HTTP status code for the different HTTP transactions between Newsboat and the Nextcloud server (normally 200, but might be different in case of an error)

---

My test setup only supports HTTP, so in my case, I could skip steps 1 and 3 and needed to filter on port 8080 instead.
For me, the resulting output shows that all HTTP transactions were successful (HTTP status code 200):
![wireshark-example](https://user-images.githubusercontent.com/4629607/137804512-82ccea6f-8e69-481b-860d-6c77a76d5499.png)

**Comment by aleprovencio** [comment] 2021-10-21 21:42
Thats great, @dennisschagt!

@Minoru, there's no need for a new issue here since it seems to belong on `NC/news`'s side, right?

**Comment by dennisschagt** [comment] 2022-04-24 16:33
@aleprovencio The issue got fixed in nextcloud-news [18.0.1](https://github.com/nextcloud/news/releases/tag/18.0.1) (via https://github.com/nextcloud/news/pull/1687)

**Comment by aleprovencio** [comment] 2022-04-25 13:01
That's awesome, thanks for the update.
I have just tried this, but unfortunately when pressing the 'mark-feed-read' keybinding it presents me the following question: 
```
Do you really want to mark this feed as read (y:Yes n:No)?
```
Pressing 'y' has no effect for me, you confirm this?

**Comment by Minoru** [comment] 2022-04-25 15:01
@aleprovencio I can not confirm. Newsboat 2.27, Nextcloud 23, News 18.0.1 — `mark-feed-read` asks for confirmation and, once <kbd>y</kbd> is pressed, marks the entire feed read in Newsboat. Once I reload the page in the browser, News also shows the feed as read.

**Comment by aleprovencio** [comment] 2022-04-25 17:46
This is odd, I even had an extra check on my keybindings as I'm not quite sure if they can interfere somehow. Anyways, for now I'm using 'confirm-mark-feed-read no' and the update on News is working as expected.

**Comment by Minoru** [comment] 2022-04-25 20:09
@aleprovencio What locale are you using? If it's not English, it might be that Newsboat is asking you in English but expects an answer in your local language (because the question and answer are separate strings, and one might have been translated while the other one wasn't).

To double-check that it's not a locale problem, try running `LC_ALL=C newsboat`. This will default to English (and ASCII, so don't panic if you don't see diacritics or if non-ASCII characters turn into question marks).

**Comment by aleprovencio** [comment] 2022-04-25 21:33
That's exactly the case @Minoru :)

**Comment by Minoru** [comment] 2022-04-26 17:47
@aleprovencio Ah, cool! If you have a minute, please edit the appropriate file in the "po" directory of this repo, and send a pull request. Poedit is a good program for that, but you can also do that with a text editor or even through GitHub itself (but don't forget to add yourself to the header at the beginning of the file then, and update the date there).
