### ISSUE TITLE
Quotes in item title leads to wrong download path

### ISSUE THREAD

**Issue by krimha** [newsboat/newsboat#457] opened 2019-03-01 15:53 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
newsboat 2.14.1
System: Linux 4.20.12-arch1-1-ARCH (x86_64)
Compiler: g++ 8.2.1 20181127
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.64.0 OpenSSL/1.1.1a zlib/1.2.11 libidn2/2.1.1 libpsl/0.20.2 (+libidn2/2.1.1) libssh2/1.8.0 nghttp2/1.36.0 (compiled with 7.64.0)
SQLite: 3.27.1 (compiled with 3.26.0)
libxml2: compiled with 2.9.9
```

Steps to reproduce the issue:
1. Set
```
download-path ~/podcasts/%n
download-filename-format %F-%t.%e
```
2. Enqueue podcast where item title has quotes in it e.g. `"Crime and Punishment" by Fyodor Dostoevsky`. One such podcast can be found [here](https://podkast.nrk.no/program/kjente_boeker_paa_4_minutter.rss) (norwegian)

3. Open podboat and download. The podcast is saved in `~/'/~/podcasts/Kjente`, where `Kjente` is the filename, and the first word of the feed name. Note the folder called `'`

**Other info you think is relevant**:
I'm only submitting this because it seems like the podcast itself works well. When the quotes are manually removed from `cache.db` before putting the item in the download queue, everything works as expected.

**Comment by Minoru** [comment] 2019-03-01 18:33
Reproduced with f03cd8d8b3cb4d5f4ed718cc48ea329b2c934baa. Thank you for the report, @krimha!

**Comment by krimha** [comment] 2019-03-03 10:28
The cause seems to be that `Stfl::quote` surrounds the text with `'`s instead of `"`s when the input contains `"`. Thus, the queue file is parsed wrongly.

What would a good solution to this be? I suppose it is possible to place the blame either on writing the "wrong" format to the queue, or parsing wrong.

**Comment by krimha** [comment] 2019-03-03 10:50
This seems to be an issue similar to #290

**Comment by Minoru** [comment] 2019-03-03 18:32
Thanks for digging into this! I'd put the blame on Newsboat and its QueueManager, i.e. the writing side. The best solution I can think of is:
1. write our own quoting function that escapes double quotes (preferably in Rust so we don't have to port it later);
2. write a test to make sure that for any string, quoting and then tokenizing with `utils::tokenize_quoted` (which Podboat uses via QueueLoader class) gets us exactly the same string, This will have to be done in C++ for now because `utils::tokenize_quoted` is not ported yet. The "any" part can be approximated with a few different inputs for now, but on the Rust side we can also use [proptest](https://crates.io/crates/proptest) to check this more thoroughly (I'm using that crate for one of my upcoming PRs, and it seems to be better than quickcheck).

**Comment by krimha** [comment] 2019-03-04 06:50
That sounds like a good solution! I would be happy to help fixing this issue. My Rust knowledge is very limited, but this seems like an overcomable rask.

**Comment by Minoru** [comment] 2019-03-04 18:09
Step 0 is checking if we already have a good enough function :) We certainly have some quoting ones, just need to look through include/utils.h (and maybe tests/utils.cpp) and see if any of them fit. If not, then proceed to step 1.

**Comment by Minoru** [comment] 2019-03-04 18:38
A test for `Stfl::quote`'s behaviour would be nice as well. Will help when we get to porting/replacing it.

**Comment by krimha** [comment] 2019-03-04 21:12
Sounds good!

**Comment by Minoru** [comment] 2019-05-25 14:03
This is fixed by https://github.com/newsboat/newsboat/commit/01c3996f92fb352fedbcd9f9e287d0b18ae7f6c2.

**Closed by Minoru** 2019-05-25 14:03 UTC
Labels: bug
