### ISSUE TITLE
Duplicate topics at feeds 

### ISSUE THREAD

**Issue by OlegPQ** [newsboat/newsboat#1402] opened 2021-01-05 18:33 UTC
Hello! Thank you for the app.

I have a little confusion about how the app works. My urls file contains the following links:

https://lobste.rs/t/go.rss "~Lobsters Go"
https://lobste.rs/t/programming.rss "~Lobsters programming"

"programming" sometimes also contains topics from "go", i.e. in this case topics can be duplicated in multiple feeds.

On the first load (clean base) I see the identical topics in both feeds, but on further loading only one of the feeds will contain topics that are duplicated. I want to see all the topics in feeds, even if they have already been duplicated. Is it possible to do this? Maybe I missed some option which allows to do this.

P.S. newsboat 2.22.0
P.S.S. hope you understand what I mean, I am sorry for my English

**Comment by Minoru** [comment] 2021-01-06 04:03
I think you're describing #898. There's no way to work around that at the moment. The items will keep "migrating" between feeds depending on the order in which feeds were reloaded. As noted in #898, we do plan to rework Newsboat a bit to give users control over this, but for now, this work is not done.

I'm closing this issue as a duplicate of #898, then. Please subscribe to that other one to get updates on this.

**Closed by Minoru** 2021-01-06 04:03 UTC
