### ISSUE TITLE
Mapping for german Ö Ä Ü "Umlaute" not working

### ISSUE THREAD

**Issue by vod3** [newsboat/newsboat#947] opened 2020-05-19 21:13 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
newsboat 2.19.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):
```
browser lynx
auto-reload yes
download-path "~/podcasts"
feed-sort-order title-dec
refresh-on-startup yes
macro m set browser "mpv %u"; open-in-browser ; set browser "elinks %u"


# binds ----------------------------------------------------------------

bind-key k down
bind-key l up
bind-key k next articlelist
bind-key l prev articlelist
bind-key K next-feed articlelist
bind-key L prev-feed articlelist
bind-key G end
bind-key g home
bind-key d pagedown
bind-key u pageup
bind-key ö open
bind-key j quit
bind-key a toggle-article-read
bind-key n next-unread
bind-key N prev-unread
bind-key D pb-download
bind-key U show-urls
bind-key x pb-delete
```

Hello there, I would like to use the jklö keys for navigation instead of the hjkl for ergonomic reasons, unfortunately I am not able to map the "ö" key for the "open" command.
All other keys work fine.  Am I missing something?
Thanks!

Steps to reproduce the issue:

1. bind ö for open in .config/newsboat/config

2. open newsboat and try to open one feed with ö

3. not opening, even freezing the program by not reacting to other keys anymore!

**Comment by dennisschagt** [comment] 2020-05-19 23:42
To debug this, it might help to run newsboat with logging at level `DEBUG`:
`newsboat --log-level=6 --log-file=log.txt`

After typing `ö` and quiting newsboat, the `log.txt` file should contain lines like the following for each registered keypress:
`[2020-05-20 01:09:09] DEBUG: KeyMap::get_operation: keycode = ö context = feedlist`

Could you check if `ö` shows up in the logfile after running newsboat with logging enabled?

---

Just a guess, but this might be caused by having different ways in unicode to represent `ö` (one way in the config file, another way when entered as Newsboat keypress):
- unicode codepoint 00F6 (letter `o` with umlaut)
![image](https://user-images.githubusercontent.com/4629607/82388411-da081e80-9a39-11ea-8d5f-5a8c55faf71b.png)
- unicode codepoint 006F (letter `o`) followed by 0308 (combining diaeresis)
![image](https://user-images.githubusercontent.com/4629607/82388679-76cabc00-9a3a-11ea-88e4-d6e58b50da91.png)

  ![image](https://user-images.githubusercontent.com/4629607/82388535-26ebf500-9a3a-11ea-8d1a-1ac4601b511e.png)

Again, this is just a guess. The log file might show if this is the case.

**Comment by vod3** [comment] 2020-05-20 06:53
strange, I always start newsboat with a sxhkd shortcut
`super +n
     alacritty -e newsboat`

in this instance the UTF characters like ÖÜÄ don't work, and the Ö shortcut isn't mapped. But starting newsboat in a new alacritty terminal manually, everything works as expected. I guess it has something to do with my terminal emulator, not newsboat related. but thanks for your help!

**Comment by Minoru** [comment] 2020-05-20 15:44
> super +n alacritty -e newsboat
> in this instance the UTF characters like ÖÜÄ don't work, and the Ö shortcut isn't mapped.

Are any other bindigs from your config mapped? This sounds like Newsboat is running in a slightly different environment, and doesn't pick up your config. My guess is that `alacritty -e CMD` runs `CMD` directly, without invoking your shell; and you probably have some important stuff (`export XDG_CONFIG_DIR`?) in your shell's configuration.

Since the problem seems to be outside of Newsboat, I'm tagging this as invalid and closing. Please comment if there are new facts that point at Newsboat; we can always re-open the issue.

Thanks for filing the issue in the first place, and thanks for using Newsboat!

**Closed by Minoru** 2020-05-20 15:44 UTC
