### ISSUE TITLE
Unable to mark all articles in a feed as read

### ISSUE THREAD

**Issue by maxigaz** [newsboat/newsboat#1932] opened 2022-01-11 13:03 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: 2.26.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
confirm-mark-all-feeds-read no
```

Steps to reproduce the issue:

1. Start Newsboat with a clean cache file, a minimal temporary config file and url file: 

	```
	newsboat -c /tmp/newsboat-cache.db -C /tmp/newsboat-config -u /tmp/newsboat-urls
	```

2. Press `r` or `R` to download at least one feed, and then open it with Enter to see its list of articles.

3. Press `A` to try to mark all articles as read.

4. The following message appears on the status bar, regardless of whether `confirm-mark-all-feeds-read no` is in the config file or not:

	```
	Do you really want to mark this feed as read (y:Yes n:No)?
	```

5. Pressing `y` doesn't do anything, only `n` does, which cancels the operation.

**Other info you think is relevant**:

I'm using Newsboat inside Zsh 5.8 and Alacritty 0.9.0 on Manjaro Linux.

**Comment by dennisschagt** [comment] 2022-01-11 20:50
> regardless of whether confirm-mark-all-feeds-read no is in the config file or not:

That setting is used when marking all feeds as read (default `C` key in the feed overview). When you mark a single feed as read (default  `A` key in feed overview and article list), the `confirm-mark-feed-read` configuration is checked instead ([documentation](https://newsboat.org/releases/2.26/docs/newsboat.html#confirm-mark-feed-read))

> Pressing y doesn't do anything, only n does, which cancels the operation.

@maxigaz: Any chance you are Hungarian? (or using the Hungarian locale?)

In the Hungarian translation, it looks like [the question text is not translated](https://github.com/newsboat/newsboat/blob/3572347c5e0d7a4bc564546211858c2a426a0fac/po/hu.po#L705-L708) (marked as "fuzzy").
If it would be translated, it would probably look something like `<question in Hungarian> (i: Igen, n: Nem)`, meaning that you would have to press the `i` key instead of the `y` key.
Could you let us know if pressing the `i` key works for you, or if you are not using the Hungarian locale?

<details>
  <summary>Relevant part of the Hungarian translation file</summary>
  
https://github.com/newsboat/newsboat/blob/3572347c5e0d7a4bc564546211858c2a426a0fac/po/hu.po#L705-L721
</details>

**Comment by maxigaz** [comment] 2022-01-12 11:16
@dennisschagt Yes, I'm using a Hungarian locale. I can confirm that pressing `i` works.

I can create a PR with the correct translation of the message later, if that's OK with you.

You are also right about `confirm-mark-feed-read`. I was a little hasty while looking for marking all articles as read in the documentation, so I mixed it up with `confirm-mark-all-feeds-read`.

Thank you for the help!

**Comment by wakatara** [comment] 2022-01-12 23:59
@dennisschagt 

I think the problem is larger than just the Hungarian version or the mark-read option being in there. 

At least in the new release 2.26.0 I am using the English version and any attempt to use Shift-a to mark a feed as read completely freezes the program for me until I hard kill my tmux pane. Adding the "confirm-mark-all-feeds-read no" to my config file does not help (I actually just came over to file the bug report and noticed this other big report.). 

Environment: 
OSX 12.1
fish shell 3.3.1
kitty 0.19.3
tmux 3.2
newsboat 2.26.0  (installed via homebrew the OSX package manager).

**Comment by Minoru** [comment] 2022-01-13 19:05
@wakatara Weird. I'm using English version too (`locale` says `en_GB.UTF-8`) under Tmux 3.1c, but on Linux and with ZSH. I just checked, and <kbd>Shift-a</kbd> works for me both in the feedlist and articlelist.

Could you attach to the frozen Newsboat process and peek at what it's doing? Something along the lines of:

```
$ pgrep newsboat
<prints out Newsboat's process identifier(s)>
$ gdb -p <Newsboat's PID>
(gdb) backtrace
<this will show a stacktrace, please post it here>
(gdb) quit
A debugging session is active.

        Inferior 1 [process 7356] will be detached.

Quit anyway? (y or n) y
$
```

There might be multiple Newsboat processes; in that case, attach to whichever you like and use `thread apply all backtrace` to get stacktraces for all of them.

**Comment by wakatara** [comment] 2022-01-15 00:28
> @wakatara Weird. I'm using English version too (`locale` says `en_GB.UTF-8`) under Tmux 3.1c, but on Linux and with ZSH. I just checked, and Shift-a works for me both in the feedlist and articlelist.
> 
> Could you attach to the frozen Newsboat process and peek at what it's doing? Something along the lines of:
> 
> ```
> $ pgrep newsboat
> <prints out Newsboat's process identifier(s)>
> $ gdb -p <Newsboat's PID>
> (gdb) backtrace
> <this will show a stacktrace, please post it here>
> (gdb) quit
> A debugging session is active.
> 
>         Inferior 1 [process 7356] will be detached.
> 
> Quit anyway? (y or n) y
> $
> ```
> 
> There might be multiple Newsboat processes; in that case, attach to whichever you like and use `thread apply all backtrace` to get stacktraces for all of them.

Hey @Minoru and @dennisschagt 

I used gdb -p on the pid (and actually ran it outside of tmux (and still appear to be having the same issue).
However, `gdb -p <pid>` just returns a compaing about being unable to find a Mach task port which I imagine is an issue with it trying to use OSX rather than linux (same as /proc/<pid>/stack not being available.). 

However, I extracted the attached from the OSX System Monitor sample. (not sure how helpful it is.).
[newsboat_dump.txt](https://github.com/newsboat/newsboat/files/7873901/newsboat_dump.txt)

It's a curious one to be sure. it's only happened with upgrading to the new version of newsboat just after Xmas (I'm a long time user - from even when it was newsbeuter.  :-) ).

thanks for any insight into this!
Daryl.

**Comment by wakatara** [comment] 2022-01-15 00:36
@dennisschagt 

If I am using remote API calls it is definitely unintentional.  =] 

Here's my config. It's a pretty simple config. Note that I use the same file on linux and osx but M1 osx is my main driver atm (I believe I am running the x86_64 version of newsboat through homebrew even though on the M1 though.). 

```
=== Config === 
# Colours
# Attempt at Nord colour scheme
# Works best with Nord kitty colour scheme set

color background          color236   default
color listnormal          color248   default
color listnormal_unread   color6     default
color listfocus           color236   color12
color listfocus_unread    color15    color12
color info                color248   color236
color article             color248   default

# highlights
highlight article "^(Feed|Link):.*$" color6 default bold
highlight article "^(Title|Date|Author):.*$" color6 default bold
highlight article "https?://[^ ]+" color10 default underline
highlight article "\\[[0-9]+\\]" color10 default bold
highlight article "\\[image\\ [0-9]+\\]" color10 default bold
highlight feedlist "^─.*$" color6 color236 bold

text-width 78
browser open
# browser "firefox %u"
# browser "xdg-open %u"
# macro m set browser "mpv %u"; open-in-browser ; set browser "xdg-open %u"
player "mpv"
macro m set browser "mpv %u"; open-in-browser ; set browser open
download-path "~/Downloads/%n"
save-path "~/Downloads"
reload-threads 20
cleanup-on-quit yes
=== END ===
```


```

**Comment by Minoru** [comment] 2022-01-17 18:17
@wakatara The callgraph in the dump is just what I was looking for, thank you! It shows that the program is waiting for input (it called into Ncurses library which in turn blocked on read()). This is normal, so I'm not sure what's going on there.

How hard is it for you to downgrade to 2.25? It'd be nice to confirm that the bug really appeared in 2.26, and wasn't caused by some other upgrade that happened at the same time (e.g. ncurses?)

One other thing you could try is to run Newsboat in C locale (`LC_ALL=C newsboat`). This will force it to English and ASCII, so some articles might not be displayed correctly, but at least it will rule out any locale-dependent weirdness.

**Comment by wakatara** [comment] 2022-01-18 01:01
@Minoru 

Heya! I downgraded to 2.25.0 from homebrew just now (surprisingly not easy using `homebrew` compared to `yay`, so via this URL https://blog.sandipb.net/2021/09/02/installing-a-specific-version-of-a-homebrew-formula/).

2.25.0 works as expected and the `A` command reads the entire thread cleanly. So, it would appear that this bug did appeared in 2.26. 

Let me know if you'd like me to try any other diagnostics to try and run this down for you (eg. compiling from source for the 2.26.0 version rather than the bottled binary etc). Happy to help run down the bug.

thanks again for trying to help me fix this. I'll stick with 2.25 until we can run this down to ground. 

ciao!
Daryl.

**Comment by Minoru** [comment] 2022-01-18 19:16
> 2.25.0 works as expected and the A command reads the entire thread cleanly. So, it would appear that this bug did appeared in 2.26.

Whoa! Not what I expected :)

It'd be cool if you could use `git bisect` to pinpoint the commit that introduced the regression. [Here's how we install the the dependencies in CI on macOS](https://github.com/newsboat/newsboat/blob/5853f8703086832aed4b68deceb20be1db5a0d1f/.cirrus.yml#L109-L126). Hopefully the commit would make it clear what's going wrong.

**Comment by wakatara** [comment] 2022-01-23 09:08
@Minoru 

Hey Alex!

Hope you're having a great weekend. 

Alright, `git bisect`-ed between r2.25 and r2.26. Git marked the following commit as the start of the problem.

```bash
60ddc830718cf38f2a01955c3cd9a37a6eecac03 is the first bad commit
commit 60ddc830718cf38f2a01955c3cd9a37a6eecac03
Author: aflyingpumpkin <b222006gamer@gmail.com>
Date:   Mon Sep 20 11:04:25 2021 -0400

    added confirm-mark-feed-read config variable

 doc/configcommands.dsv     |  1 +
 src/configcontainer.cpp    |  1 +
 src/feedlistformaction.cpp | 49 +++++++++++++-----------
 src/itemlistformaction.cpp | 93 ++++++++++++++++++++++++----------------------
 4 files changed, 78 insertions(+), 66 deletions(-)
```

Been a while since I messed with cpp so might not be that useful in drilling down on the C++ code (was rather hoping it was a Rust problem since been spending most of my time the past few months learning that), so lemme know if there is anything further I can do to run this thing down for you.

thanks!
Daryl.

**Comment by Minoru** [comment] 2022-02-02 18:52
@wakatara It was a very good weekend, never found time to look further into this :) But I stared at the commit for a few minutes just now, and I still don't see anything wrong with it.

Perhaps it's the entire question-and-answer machinery that's broken? Can you please back up your cache.db and run a few more experiments:

1. set `confirm-mark-all-feeds-read yes` (which is the default, but anyway) and press <kbd>C</kbd> in the feeds list. Does it hang waiting for you confirmation?
2. set `confirm-exit yes` and press <kbd>q</kbd> to quit Newsboat. Does it hang?
3. I see you have `save-path` set — I take it Newsboat does not hang when you're saving an item?

**Comment by Minoru** [comment] 2022-02-11 19:47
> Apologies. Probably not what you wanted to hear. I had hoped it was something much simpler and a trivial fix.

It's none of your fault ;) At least this bug will make for a good story once we manage to pinpoint and fix it :D 

Okay, I got a couple more asks:

1. when saving an article, try choosing a name that already exists — Newsboat should ask you if you'd like it overwritten, and hang (this code path goes through `View::confirm()` just like the rest, it'd be weird and interesting if it didn't hang);
2. can you bisect when `confirm-exit yes` started hanging? This setting is ancient, so pick the oldest Newsboat release that you can still build, and start with that. Also, the rest of your confirm is probably irrelevant to this, so run Newsboat like this: `newsboat --config-file=your-file-with-just-confirm-exit-in-in --cache-file=/dev/shm/cache.db --url-file=a-file-with-a-single-feed-in-it` The cache is in tmpfs because you don't really need this data, and it'd be a small file anyway. The point of this ask is: I'm fairly sure now that `View::confirm` is at fault, so we need to figure out when it started causing problems.

Thanks a lot for your help! It's tough to fix bugs when one can't reproduce them, so I appreciate the help in figuring things out.

**Comment by pittavini** [comment] 2022-03-04 15:39
Hi all
I am running Newsboat 2.26.0 installed via brew english version on an M1,  the Q&A functionality seems to be working fine without hanging.  I tried different scenarios 

confirm-mark-all-feeds-read yes
confirm-exit yes

Also 
confirm-mark-feed-read false
I couldn't get it to hang
best regards
giuseppe

**Comment by wakatara** [comment] 2022-03-04 17:52
@pittavini 

That is maddening. I just looked at this again, commented out most of my config, nuked the cache and retried this and still get a hang trying the same config options. 

Quick question if you're on an M1 and Monterrey: I'm assuming you've installed newsboat via homebrew. If you have, are you using the native M1 version (so in /opt/... ) or are you on the M1 and using the x86_64 version of the same? (I need to stick to x86_64 since been running for a while and need some critical libraries that are not yet working on M1.)

**Comment by pittavini** [comment] 2022-03-04 20:39
@wakatara 
Correct native M1 version, so probably that's the reason I can't repro it. ;)

**Comment by wakatara** [comment] 2022-03-05 03:10
@pittavini 

That's an important clue though then. If it only an issue with x86_64 version on M1 architecture and not the native compiled M1 version on homebrew.

**Comment by wakatara** [comment] 2022-03-05 06:48
@pittavini 

Sorry, can you just reconfirm you installed the newsboat via homebrew and it's arm64? (and did not compile natively or use some other install method?). 

I literally nuked my entire homebrew installation, switched from x86_64 to arm64 and I'm *still* getting hanging on All read. 

If it works for you and that is true, I am wondering if it has something to do with my shell (fish) or fact I am using it in tmux. 🤔

**Comment by pittavini** [comment] 2022-03-07 16:40
@wakatara 
I have two versions of newsboat; one I built from source code and one installed using homebrew.  Using the two versions I cannot reproduce the issue you having.
Having newsboat inside a tmux session or zsh doesn't make a difference for me, _mark all read_ still works as expected.  I don't use fish so I cannot confirm if this is an issue.

**Comment by wakatara** [comment] 2022-03-08 06:48
@pittavini 
At this point, I'm stumped, I gotta admit. 

To try to isolate variables, I've used 2.26 and still get the hanging behaviour
1. with and without tmux
2. in fish and in zsh (even switching default shells)
2. with minimized config file down to just not asking for All Read confirmations
3. Uninstalled via brew, brew autoremoved dependencies, and then compiled from source in homebrew

I'm now wondering whether it's a dependency like json-c or similar. 

One last check... you're on OSX M1 with _Monterey_, right?

**Comment by pittavini** [comment] 2022-03-08 07:36
@wakatara 

right monterey 12.2.1, the hanging behavior is only in the question y/n or does it happen when you read feeds too?

**Comment by wakatara** [comment] 2022-03-08 07:43
Just when I try to mark feeds All Read (even if it the option is set to
false `confirm-mark-all-feeds-read false` explicitly or that option is not
present in the config file.

I did some tests from Alexander's asks and Q&A type question like confirm
before exit will also cause the hang behaviour.

¯\\_(ツ)_/¯

I will try after work and dinner to compile directly from source and take
this out of homebrew entirely to see if that does not trigger the problem.
(I am very surprised it's working for you tbh... now I'm also wondering if
it is perhaps one of the feeds I have and some sort of parsing issue since
that's about the only other thing I can think of. 🤔 ).

Hehe... it is an interesting mystery though.  🕵🏼‍♂️

**Comment by Minoru** [comment] 2022-03-08 18:53
> now I'm also wondering if it is perhaps one of the feeds I have and some sort of parsing issue since that's about the only other thing I can think of. thinking

This should be easy enough to test:

1. create a file somewhere, let's call it 1932-urls, and put `https://newsboat.org/news.atom` in it;
2. run Newsboat like this: `newsboat --cache-file=/tmp/1932-cache.db --url-file=1932-urls --config-file=/dev/null`;
3. check if it still hangs.

This totally isolates Newsboat from your existing config and data.

**Comment by Daryl-DH** [comment] 2022-03-10 17:46
Alright, @Minoru and @pittavini 

You guys are going to laugh when I tell you what I tracked down.

I tried the method above to test it was my urls. System doesn't hang. OK, must be one of my feeds... but also noted that the message to confirm the entire feed was read popped up. 

So, I start removing feeds. Still hanging... hmmm... also, why don't I see the confirm message? So, I hit y as a key next... and... the feed is read. 

What I'm *guessing* happened in 2.26:

1. The default behaviour for `confirm-mark-feeds-read` changed to true (triggering a confirm dialogue on A to read the feeds if it was not set in the config file.)
2. The theme I use (Nord) from contrib... does not pop up a visible dialogue message in the space below the info bar for some reason - it seems invisible but obviously happens - so may be related to the colour scheme (since it works in a naked config file.). 

I added `confirm-mark-feeds-read false` into my config file so now a simple `A` reads the feed when I'm done. 

More to the point though, how do I fix the Nord colour scheme to make sure I see the pop up norification? I"m assuming it is a colour scheme issue - so curioous as to what controls the notification messages text in the colour scheme options so I can fix it (I am embarrassingly also the author of that theme from 3 years ago... 8-/ ).

Anyhow, lemme know if I've guessed right. I am quite pleased it's not a more serious problem though! 
(and omg, sorry for all the trouble in tracking down what looks like a display rather than code problem.).

**Comment by Minoru** [comment] 2022-03-11 19:56
Wow, that's an unexpected turn! But I'm sure glad that the mystery is now solved. Great work @wakatara!

To fix the nord colorscheme, change the first argument for the `background` element:

```
color background          color236   default
```

`color236` is very close to the `default` black. I changed it to `red` for testing, but you can probably pick a more pleasant hue :)

**Comment by Minoru** [comment] 2022-03-11 20:03
I just tested all the colorschemes, and as of 2f9254aeab62d29045ef81a71bb7a7d45abf8690 only "nord" exhibits this problem. I didn't use any custom colour palettes in my terminal though; I hope that themes like Solarized don't stray too far from the progression of the colours.

I consider this fixed. @wakatara, please send a PR to fix "nord" once you've found a good colour to use there :) And thanks once again for finding the root cause!

**Closed by Minoru** 2022-03-11 20:03 UTC
Labels: bug, i18n

**Comment by Daryl-DH** [comment] 2022-03-12 02:13
@Minoru 

Yup... will give fixes a play on the plane. The highlight on unread items also needs tweaking.

Hmmm... considering the prevalence of dark mode and dark backgrounds themes, should there also perhaps be a  Feature Request here to create the ability to colour prompts as an option in the configs file?  I could see a definite desire to have that styled separately from the background colour.

I believe (I am not an expert on terminal colorschemes), color236 when you have the Nord palette in terminal sits in line with its palette so just wondering if this is a general problem on dark background themes.

**Comment by wakatara** [comment] 2022-03-12 03:37
@Minoru 

Ignore the prompt FR question. I see what I did. That's what I get for trying to be fancy. I've played with this this morning over breakfast and using the default Nord palette works *way* nicer (once I stopped being fancy). Will put in a PR shortly. 
Thanks!
