### ISSUE TITLE
Newsboat -v does'nt give current version information 

### ISSUE THREAD

**Issue by edi9999** [newsboat/newsboat#579] opened 2019-07-15 08:42 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

```
$ newsboat -v 

newsboat  - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2019 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2019 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
It bundles an alphanum algorithm implementation licensed under the MIT license: http://www.davekoelle.com/alphanum.html

newsboat
System: Linux 4.15.0-54-generic (x86_64)
Compiler: g++ 7.4.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.58.0 GnuTLS/3.5.18 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3 (compiled with 7.58.0)
SQLite: 3.22.0 (compiled with 3.22.0)
libxml2: compiled with 2.9.4
```

Steps to reproduce the issue:

    version=2.16.1
    if newsboat --version | grep -F "newsboat $version"
    then
        echo "newsboat $version already installed"
        return 0
    fi
    url="https://newsboat.org/releases/$version/newsboat-$version.tar.xz"
    curl -sSL "$url">"newsboat.tar.xz"
    atool -x newsboat.tar.xz
    cd "newsboat-$version"
    make
    sudo make install

After running this bash script, `newsboat --version` and `newsboat -v` show the following first line : `newsboat  - https://newsboat.org/`, but 2.16.1 is nowhere to be found in the output.

I think this was not the case on previous releases.

**Comment by j605** [comment] 2019-07-15 17:09
I can't reproduce this by checking out the r2.16.1 tag.

**Comment by Minoru** [comment] 2019-07-15 17:40
Couldn't reproduce from the tag either, but did reproduce from a tarball as @edi9999 described. Fascinating, because there's basically nothing that could be broken here—and yet it's broken :) I'm investigating.

**Comment by Minoru** [comment] 2019-07-15 18:20
The problem was caused by us running `git describe` and using its output without checking if it exited successfully. In 2.16.1 we didn't even check if the command started; this has been fixed in master, but the other half remained—we need to check if the command finished all right. I just submitted a PR that adds a check.

This is the second bug in that 16-line build script. I'm starting to doubt my abilities as a programmer ._.

**Comment by edi9999** [comment] 2019-07-16 14:55
Can you also add treatment if the command fails ?

I usually like to think I will always handle errors (first), then only the main case, so that all potential errors are catched and not ignored. Also it has the advantage that the main case (without error) has no indentation.

Something like : 

```
if !hash_output.status.success() {
   fail('miserably') // dont no any rust ...
}
println!("cargo:rustc-env=GIT_HASH={}", hash);	            let hash = String::from_utf8_lossy(&hash_output.stdout);
// Re-build this crate when Git HEAD changes. Idea lifted from vergen crate.
println!("cargo:rustc-env=GIT_HASH={}", hash);
println!("cargo:rebuild-if-changed=.git/HEAD");	            // Re-build this crate when Git HEAD changes. Idea lifted from vergen crate.
println!("cargo:rebuild-if-changed=.git/HEAD");
```

**Comment by Minoru** [comment] 2019-07-16 19:32
Oh, it *is* handled, just not in build.rs. [`utils::program_version()`](https://github.com/newsboat/newsboat/blob/84e8c6a4976cb065f1ea445e312e1581917706ef/rust/libnewsboat/src/utils.rs#L505) checks the value of `GIT_HASH` (at compile time) and uses it if it's non-empty. Otherwise the program version is determined by the version of the "libnewsboat" crate; this cannot fail.

But now that I written the above paragraph, it occurs to me that I could make this clearer by moving all the logic into build.rs, which will set `PROGRAM_VERSION` or something, which is then used by `utils::program_version()`. I'll go update my PR; thanks for the inspiration :)

**Closed** 2019-07-18 17:50 UTC
Labels: bug
