### ISSUE TITLE
Feed reload resets articleview position

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#387] opened 2018-12-11 18:59 UTC
**Newsboat version (copy from `newsboat -v`)**: 2.13 81d378434b7f16ec6377d899eed2b1b807da356a

Steps to reproduce the issue: same as #384

If reload brought no new items to current feed, current position in articleview will be reset (i.e. you'll end up on the first line of the article). If reload brought new items (i.e. `cache::externalize_rssfeed` and `cache::internalize_rssfeed` were called), you'll get #384, which will mask this bug.

As @zaowen found in #386, reset happens [here](https://github.com/newsboat/newsboat/blob/81d378434b7f16ec6377d899eed2b1b807da356a/src/itemviewformaction.cpp#L132). But if we remove this line, other stuff breaks:
* if you're in the middle of an article and go to another one (`n`, `p`, `J`, `K`), you'll see the middle of another article (because the pager remembered its position instead of resetting it)
* if you switch to source view with ^U, you'll start viewing HTML from the middle rather than beginning

I'm not entirely sure how to best fix this. It seems like redraws should be decoupled from resets—but then, why even redraw if nothing changed?

**Comment by Minoru** [comment] 2020-11-28 16:02
This is coupled (or at least related) to #1298.

**Comment by dennisschagt** [comment] 2023-09-30 13:55
It looks like this is fixed by https://github.com/newsboat/newsboat/pull/2075
I can no longer reproduce it, git bisect points to https://github.com/newsboat/newsboat/commit/f9e616b7c4ee90911c154242d980f4d404346344

**Closed by dennisschagt** 2023-09-30 13:55 UTC
Labels: bug
