### ISSUE TITLE
Support Media RSS extension in Atom

### ISSUE THREAD

**Issue by danrobi11** [newsboat/newsboat#1173] opened 2020-09-05 13:57 UTC
Hello 
Youtube video description are usually loaded when fetching new feed. (with other feed clients) Although, not in newsboat.
How do I fetch youtube video description with newsboat?

**Comment by Minoru** [comment] 2020-09-05 14:21
Hi. Can you please follow the issue template? I've no idea what Newsboat version you're running and don't have a feed URL to reproduce this.

**Comment by danrobi11** [comment] 2020-09-05 23:55
My bad
```
"https://www.youtube.com/feeds/videos.xml?channel_id=UC5aeU5hk31cLzq_sAExLVWg" htmlUrl="https://www.youtube.com/channel/UC5aeU5hk31cLzq_sAExLVWg"
```
newsboat 2.13.0
System: Linux 4.19.0-10-amd64 (x86_64)
Compiler: g++ 8.3.0

**Comment by Minoru** [comment] 2020-09-06 12:05
YouTube uses Atom but puts the description into [Media RSS tags](https://www.rssboard.org/media-rss):

```
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns:yt="http://www.youtube.com/xml/schemas/2015" xmlns:media="http://search.yahoo.com/mrss/" xmlns="http://www.w3.org/2005/Atom">
 <link rel="self" href="http://www.youtube.com/feeds/videos.xml?channel_id=UC5aeU5hk31cLzq_sAExLVWg"/>
 <id>yt:channel:UC5aeU5hk31cLzq_sAExLVWg</id>
 <yt:channelId>UC5aeU5hk31cLzq_sAExLVWg</yt:channelId>
 <title>Ruptly</title>
 <link rel="alternate" href="https://www.youtube.com/channel/UC5aeU5hk31cLzq_sAExLVWg"/>
 <author>
  <name>Ruptly</name>
  <uri>https://www.youtube.com/channel/UC5aeU5hk31cLzq_sAExLVWg</uri>
 </author>
 <published>2012-11-06T23:43:45+00:00</published>
 <entry>
  <id>yt:video:c8OZYfvEHto</id>
  <yt:videoId>c8OZYfvEHto</yt:videoId>
  <yt:channelId>UC5aeU5hk31cLzq_sAExLVWg</yt:channelId>
  <title>Journalism on Trial *PARTNER CONTENT*</title>
  <link rel="alternate" href="https://www.youtube.com/watch?v=c8OZYfvEHto"/>
  <author>
   <name>Ruptly</name>
   <uri>https://www.youtube.com/channel/UC5aeU5hk31cLzq_sAExLVWg</uri>
  </author>
  <published>2020-09-06T11:31:00+00:00</published>
  <updated>2020-09-06T11:31:01+00:00</updated>
  <media:group>
   <media:title>Journalism on Trial *PARTNER CONTENT*</media:title>
   <media:content url="https://www.youtube.com/v/c8OZYfvEHto?version=3" type="application/x-shockwave-flash" width="640" height="390"/>
   <media:thumbnail url="https://i4.ytimg.com/vi/c8OZYfvEHto/hqdefault.jpg" width="480" height="360"/>
   <media:description>Subscribe to our channel! rupt.ly/subscribe

The British government goes to great lengths to talk about its commitment to media freedom and the security of journalists around the world. But we've found that the reality of the situation appears to be drastically different.

WikiLeaks co-founder Julian Assange remains in a high-security prison in a London, with the prospect of extradition to the US where the Trump administration could sentence him to up to 175 years in prison.

In addition to widespread criticisms of Assange's treatment by the UK, Redfish has heard from experts about the mass surveillance and threats to British journalists investigating crimes that the British security services have reportedly colluded in. In fact, there appears to be a long list of threats to journalism and press freedom in Britain today. 

English subtitles are available upon request from Ruptly's Client Desk (cd@ruptly.tv).

    Video ID: 20200905-056

    Video on Demand: https://ruptly.tv/videos/20200905-056
    Contact: cd@ruptly.tv    

    Twitter: http://twitter.com/Ruptly
    Facebook: http://www.facebook.com/Ruptly</media:description>
   <media:community>
    <media:starRating count="0" average="0.00" min="1" max="5"/>
    <media:statistics views="7"/>
   </media:community>
  </media:group>
 </entry>
</feed>
```

Right now, Newsboat only supports that RSS extension for RSS feeds, but there is no reason not to add support to Atom parser as well. I'll merge a PR implementing that.

Thanks for the report, @danrobi11!

**Comment by Minoru** [comment] 2020-09-06 13:05
Um, actually, this is a duplicate of #595, so I'm closing this in favour of that issue.

**Closed by Minoru** 2020-09-06 13:05 UTC
Labels: enhancement
