### ISSUE TITLE
Query parameters should not be included in downloaded filenames

### ISSUE THREAD

**Issue by ajgrf** [newsboat/newsboat#316] opened 2018-10-13 11:45 UTC
**Newsboat version (copy from `newsboat -v`)**: newsboat 2.12.0

Steps to reproduce the issue:

1. Enqueue a podcast episode with a query parameter in its download URI. I think this includes every Libsyn-hosted podcast. Try adding `http://onlinegreatbooks.libsyn.com/rss` to your `urls` file for an example.

2. Download an episode.

3. Filename ends in something like `.mp3?dest-id=703095`.

**Other info you think is relevant**:

**Comment by Minoru** [comment] 2018-10-14 12:48
Hi, thanks for the report! This is a duplicate of #183, which has been fixed with #267. The fix will be released as part of 2.14, probably on 23rd of December.

In the meantime, your only option is to build Newsboat directly from Git.

**Closed by Minoru** 2018-10-14 12:48 UTC
