### ISSUE TITLE
Fails to build on armhf in filter/Scanner.cpp

### ISSUE THREAD

**Issue by popey** [newsboat/newsboat#51] opened 2017-11-08 00:36 UTC
I'm trying to build newsboat r2.10.1 as a snap. It builds fine for i386 and amd64 but not armhf.

Build logs are available on launchpad https://launchpad.net/~build.snapcraft.io/+snap/4dacae8ecd31a1fcb3ab170cd9e62e17-xenial

Specifically this one for armhf:- https://launchpadlibrarian.net/344882746/buildlog_snap_ubuntu_xenial_armhf_4dacae8ecd31a1fcb3ab170cd9e62e17-xenial_BUILDING.txt.gz

The actual error is:-

```
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10.1\" -I/usr/include/libxml2 -I/usr/include/json-c -D_GNU_SOURCE -I/usr/include/ncursesw -DHAVE_OPENSSL=1 -o src/strprintf.o -c src/strprintf.cpp
g++ -std=c++11 -ggdb -Iinclude -Istfl -Ifilter -I. -Irss -Werror -Wall -Wextra -Wunreachable-code -DLOCALEDIR=\"/usr/local/share/locale\" -DGIT_HASH=\"r2.10.1\" -I/usr/include/libxml2 -I/usr/include/json-c -D_GNU_SOURCE -I/usr/include/ncursesw -DHAVE_OPENSSL=1 -o filter/Scanner.o -c filter/Scanner.cpp
filter/Scanner.cpp: In member function ‘Token* Scanner::NextToken()’:
filter/Scanner.cpp:588:12: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
            ^
filter/Scanner.cpp:588:26: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
                          ^
filter/Scanner.cpp:588:42: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
                                          ^
filter/Scanner.cpp:588:56: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
                                                        ^
filter/Scanner.cpp:588:86: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
                                                                                      ^
filter/Scanner.cpp:588:100: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
    if ((ch >= L'-' && ch <= L'.') || (ch >= L'A' && ch <= L'Z') || ch == L'_' || (ch >= L'a' && ch <= L'z')) {AddCh(); goto case_3;}
                                                                                                    ^
```

The configuration / build setup can be seen in the snapcraft yaml in the snapcrafters repo at https://github.com/snapcrafters/newsboat/blob/master/snap/snapcraft.yaml

Has anyone successfully built 2.10.1 on armhf yet? Something specific to the way I'm building it, or is it known broken?

**Comment by Minoru** [comment] 2017-11-08 16:46
Hi, thanks for opening the issue! This looks like a duplicate of #43. Can you check if patch from https://github.com/newsboat/newsboat/commit/ca789ed64bf71281b6a998da41032270748aa90e fixes it for you, too?

By the way, there was an attempt to create a Snap package for Newsbeuter (our parent project), but I never heard back about the results; see akrennmair/newsbeuter#456

**Comment by popey** [comment] 2017-11-08 18:20
Yup, that patch fixes it.

**Comment by Minoru** [comment] 2017-11-08 18:26
I'll be closing the issue, then. The patch will be part of the next release; you'll have to apply it to 2.10.1 until then. It's harmless, so you can do it on all platforms and not just armhf.

**Comment by Minoru** [comment] 2017-11-08 18:26
I'll be closing the issue, then. The patch will be part of the next release; you'll have to apply it to 2.10.1 until then. It's harmless, so you can do it on all platforms and not just armhf.

**Closed by Minoru** 2017-11-08 18:26 UTC
Labels: question

**Comment by popey** [comment] 2017-11-08 18:36
I've applied it to the armhf version I pushed to the snap store. So people on armhf can "snap install newsboat" and get the patched version.
