### ISSUE TITLE
Artefacts remain from the previous article

### ISSUE THREAD

**Issue by bitigchi** [newsboat/newsboat#2572] opened 2023-10-02 22:11 UTC
Version:
```
Newsboat 2.33.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2023 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2023 Newsboat contributors

Newsboat, MIT Lisansı ile lisanslanmış özgür yazılımdır. (Tüm metni görmek için `newsboat -vv' yazın.)
Şunlarla birlikte gelir:
- JSON for Modern C++ kitaplığı, MIT lisansı ile lisanslanmıştır: https://github.com/nlohmann/json
- optional-lite kitaplığı, Boost Software License ile lisanslanmıştır: https://github.com/martinmoene/optional-lite
- expected-lite kitaplığı, Boost Software License ile lisanslanmıştır: https://github.com/martinmoene/expected-lite

Newsboat 2.33.0
System: Darwin 22.6.0 (x86_64)
Compiler: g++ Apple LLVM 14.0.3 (clang-1403.0.22.14.1)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libcurl: libcurl/8.1.2 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.51.0 (compiled with 7.87.0)
SQLite: 3.39.5 (compiled with 3.39.5)
libxml2: compiled with 2.9.13
```

Config:
```
auto-reload yes
browser "links %u"
text-width 80

bind-key j down
bind-key k up
bind-key j next articlelist
bind-key k prev articlelist
bind-key J next-feed articlelist
bind-key K prev-feed articlelist
bind-key G end
bind-key g home
bind-key d pagedown
bind-key u pageup
bind-key LEFT quit
bind-key RIGHT open
bind-key l open
bind-key h quit
bind-key n next-unread
bind-key N prev-unread

itemview-title-format "%T (%u/%t)"

macro m set browser "/usr/local/bin/mpv %u"; open-in-browser ; set browser "/usr/local/bin/links %u"
macro f set browser "/usr/bin/open -a /Applications/Safari.app %u" ; open-in-browser ; set browser "links %u"
macro g set browser "/usr/local/bin/links %u" ; open-in-browser

color listfocus default blue
color listnormal_unread green default
color listfocus_unread default blue

max-items 1000
```

Steps to reproduce the issue:

1. Open a feed
2. Press n to switch to the next article in the feed
3. Continue this for a few times

Expected:
- Next article should display with its sole contents

Actual:
- Artefacts from the previous article remains on the bottom part of the current article. See screenshot:
- The issue is present for the last few versions

![Ekran Resmi 2023-10-03 01 03 26](https://github.com/newsboat/newsboat/assets/2769571/36162f08-1b6f-4860-b180-708138d219d6)

**Comment by Minoru** [comment] 2023-10-04 19:33
I can't reproduce on Linux with Newsboat r2.33-14-ga88ab. Tried it in Gnome Terminal (`TERM=xterm-256color`), with and without Tmux 3.3a (`TERM=screen-256color`).

A couple questions:
1. does pressing <kbd>^L</kbd> fixes it?
2. have you tried a different terminal emulator? Apparently you're using ncurses 5.7.20081102, perhaps it doesn't work too well with a newer terminal emulators?

**Comment by bitigchi** [comment] 2023-10-05 11:02
1. It does
2. I tried with macOS Terminal, the issue persists. Also, I've downloaded the recent `ncurses` using `brew`, but `newsboat` does not seem to pick it up. How to make it use it?

**Comment by Minoru** [comment] 2023-10-05 19:55
Apparently Homebrew builds Newsboat in such a way that it uses Ncurses shipped with macOS:

https://github.com/Homebrew/homebrew-core/blob/e1a7081e30c5f7e646f704540b861a14ad972543/Formula/n/newsboat.rb#L29

I don't know if there's a way to make it use Brew's ncurses, other than building Newsboat from source. On Linux I'd try `LD_LIBRARY_PATH`, but I don't know where Brew puts ncurses libraries and I don't know if macOS' linker even supports this environment variable.

Considering <kbd>^L</kbd> fixes it, this is definitely not Newsboat's bug; it's something to do with Ncurses, the terminal emulator, or both.

I'll keep this open in hopes that someone with a Mac also ran into this and has a solution.

**Comment by bitigchi** [comment] 2023-10-05 20:49
Well let's see what version of `ncurses` shipped with Sonoma, maybe that'll fix it.

Thanks for the investigation! It's a trivial bug at best.

**Comment by youvegottabecrazy** [comment] 2023-11-12 18:53
I reliably get this with tmux 2.1. 
I never get this with tmux 3.3a.
FYI

**Comment by bitigchi** [comment] 2023-11-13 03:55
I haven't encountered this with Sonoma.

**Comment by Minoru** [comment] 2023-12-11 18:27
Cool!

@youvegottabecrazy, have you tried this with macOS Sonoma?

**Comment by gilcu3** [comment] 2024-06-04 08:26
I am on `Archlinux` and for some reason after the last system update (which does not seem to have changed the `newsboat` version) I am getting this type of screen issue as well. It is hard to reproduce though, happens only sometimes, not sure exactly what triggers it.
I am using `wezterm` when getting the artifacts, will try to reproduce with `terminator` as well.

**Comment by Minoru** [comment] 2024-06-04 21:04
@gilcu3 Does pressing ^L (control-l) fix the problem? If it does, then the issue is with the terminal, ncurses, or tinfo (a database used by ncurses to understand what commands a terminal supports). If it doesn't, it means the bug if with Newsboat (or maybe it's a very bad bug in Ncurses, but we haven't ever encountered that, so let's hope it's Newsboat).

**Comment by gilcu3** [comment] 2024-06-05 09:54
@Minoru yes, pressing ^L fixes the issue. I just managed to reproduce it with `wezterm` but not with `terminator`, therefore maybe the problem is on their side. 

By default, `wezterm` uses `TERM=wezterm`. If before starting `newsboat` I set `TERM=xterm-256color` the problem does not happen. Do you know where should this be reported?

**Comment by Minoru** [comment] 2024-06-05 17:58
I think that changing the `TERM` means the problem is with tinfo, which is maintained by ncurses, so this should be reported to them (https://invisible-island.net/ncurses/ncurses.faq.html#report_bugs). However, it might be useful to talk to wezterm developers first; find out if you can collect some debug information to help ncurses developers figure out what exactly is wrong.

I'm closing this because the original reporter no longer experiences the bug after upgrading ncurses, the other person disappeared, and the problem you discovered seem to not be caused by Newsboat.

**Closed by Minoru** 2024-06-05 17:58 UTC
Labels: help wanted
