### ISSUE TITLE
Query feeds do not reload like normal feeds 

### ISSUE THREAD

**Issue by ottopiramuthu** [newsboat/newsboat#978] opened 2020-06-03 23:37 UTC
While normal feeds can be `reload`ed one at a time, query feeds must be reloaded using `reload-all`.

**Newsboat version**:
newsboat 2.10.2
**Settings**:
`~/.config/newsboat/config`:
```
auto-reload no
reload-only-visible-feeds no
reload-time 5
suppress-first-reload yes
reload-threads 4
bind-key r reload
bind-key R reload-all
prepopulate-query-feeds yes
```
`~/.config/newsboat/urls`:
```
https://xkcd.com/rss.xml "!xkcd" Webcomic Science CS Math xkcd
https://explainxkcd.com/rss.xml "!explainxkcd" Webcomic Science CS Math xkcd
"query:xkcd:tags # \"xkcd\""
```

**Steps to reproduce the issue**:
1. Open newsboat
2. Press 'r' to reload query feed: does nothing
3. Press 'R' to reload all feeds: query feed is successfully loaded

**Other info you think is relevant**:
If a query feed was never loaded before, it is also impossible to "open" it and reload the component feeds (e.g. xkcd and explainxkcd) separately.

**Comment by Minoru** [comment] 2020-06-04 06:03
Hi! This is just how query feeds work; they search the database for anything that matches the query. In your case, it's easy to tell which feeds will contribute to the query feed, but in general, it's not so. Consider a query feed that matches on article title:

```
"query:Posts about Newsboat:title =~ \".*Newsboat.*\""
```

Newsboat can't tell what feeds might contain matching articles, so it searches all of them.

Does that make sense, @ottopiramuthu?

**Comment by ottopiramuthu** [comment] 2020-06-04 12:37
Thank you for the response!

That makes sense. On a slower internet connection and with many feeds, it's a pain to `reload-all` when only a couple of feeds need to be reloaded. I'll stick to using query feeds for more general things like unread feeds until my internet connection improves :)

**Comment by Minoru** [comment] 2020-06-04 13:12
Yeah, slow connections are miserable. You can try increasing `reload-threads` further, but note that you might start getting errors if you make too many simultaneous requests to a single site. If all your feeds are on different domains, though, it should be safe to set `reload-therads` to the number of feeds you have.

I guess the issue is resolved now, so I'm closing it. Thanks for using Newsboat!

**Closed by Minoru** 2020-06-04 13:12 UTC
Labels: question
