### ISSUE TITLE
Is it possible to fetch new notifications in the background?

### ISSUE THREAD

**Issue by 5c0tt1** [newsboat/newsboat#1409] opened 2021-01-07 20:14 UTC
Hi, first let me **thank you for this, its amazing!**
I was wondering if it was possible to:
- Fetch new notifications in the background without opening `newsboat`?

### Why?
Tmux's bottom bar updates at any chosen interval e.g 60 seconds, so I would like a way of showing new notifications in Tmux's bottom bar! for example, the number of notifications could be shown like so: `[3]`

If not, then even a cronjob that I could run and fetch for new notifications, that way it would be possible to use bash's `PROMPT_COMMAND` to fetch this value and show it above your PS1 prompt (ZSH also!).

This would give a more seamless feel to newsboat, notifications would appear in the bar/prompt as they arrive, without opening up an app, much like a mobile phone shows notifications in the status bar as they arrive, without needing to open an app first.

**Thank you again for newsboat, your time and efforts are appreciated alot!**

**Comment by Minoru** [comment] 2021-01-08 10:11
Yes, it's indeed possible, by combining a couple of Newsboat's features:

1. write a cron job (or systemd timer or whatever) to run `newsboat -x reload` — this starts the program without a user interface, reloads all feeds, and quits;
2. configure [`notify-program`](https://newsboat.org/releases/2.22/docs/newsboat.html#notify-program) to write notification to a file which you can read from `PROMPT_COMMAND` or whatever.

Note that only one instance of Newsboat can access the same cache.db at a time, so you won't be able to start Newsboat UI while the cronjob is running.

Would that work for you?

**Comment by Minoru** [comment] 2021-01-15 13:32
Well, I think I answered the question, so I'm closing this. Don't hesitate to comment here if something is still unclear, @5c0tt1!

**Closed by Minoru** 2021-01-15 13:32 UTC
Labels: question

**Comment by explorer422** [comment] 2021-07-09 13:01
Hi, I set up my cron to auto-reload all the feed as mentioned above: ` *  12   *    *    *   newsboat -x reload` to reload the feed at 12:00. Oddly, I didn't updated the feed as I expected. But newsboat reloaded when I ran the same command through terminal. I've already test the scron using simple command like `touch ~/test.txt` and it ran as intended. So I would like to know if the way I set up the cron was the wrong way or something else?

Info:
Void Linux amd64 musl
Scron

Best.

**Comment by Minoru** [comment] 2021-07-15 14:13
Hi @explorer422, sorry for the late response! The invocation looks correct to me. Are you sure there were no other Newsboat instances running at 12:00? As noted above, only one Newsboat instance can run at a single time.

If that's not the cause, then you should look at the cron output, perhaps that'll give you more hints. Also look at the exit code — perhaps the process is killed by something? Or perhaps it crashes by itself; we got a couple bugs related to Void and musl.

Feel free to open a new issue if you find hints that you can't interpret, we'll try to help.

**Comment by explorer422** [comment] 2021-07-16 11:11
Hi @Minoru thank you for your reply. I am sure that there was only one instance running when I was testing. Because after knowing that it didn't reload I just manually set the cron job one or two minutes a head and just sit there and wait for the cron job reached it schooled time but nothing happened.
> Feel free to open a new issue if you find hints that you can't interpret, we'll try to help.

I will try and figured it out. Thanks again. :)
