### ISSUE TITLE
Feed from https://www.archlinux.org/feeds/news/ does not show any entries

### ISSUE THREAD

**Issue by rnestler** [newsboat/newsboat#689] opened 2019-10-25 15:01 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
% newsboat --version
newsboat r2.17.1 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2019 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2019 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json

newsboat r2.17.1
System: Linux 4.15.0-66-generic (x86_64)
Compiler: g++ 7.4.0
ncurses: ncurses 6.1.20180127 (compiled with 6.1)
libcurl: libcurl/7.58.0 GnuTLS/3.5.18 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3 (compiled with 7.58.0)
SQLite: 3.22.0 (compiled with 3.22.0)
libxml2: compiled with 2.9.4
```
Steps to reproduce the issue:

1. Add https://www.archlinux.org/feeds/news/ to urls

2. Try to refresh it

3. Shows 0 articles

Interesting is, if I try to open the URL in the browser it tries to download the rss xml file. Maybe that is related

**Comment by Minoru** [comment] 2019-10-25 17:51
Hi! It works for me =\

The fastest way to figure this out would be to enable debug logging (`--log-level=6 --log-file=newsboat.log`), reload the feed, and look at the log—somewhere in the middle will be a message with everything that's been downloaded from the network, plus E-Tag and Last-Modified headers.

The most usual cause for this sort of error is sites that white-list User Agents, refusing to serve RSS to anyone but the trusted programs. Since I can download the feed just fine, it doesn't seem to be the case here, though. Perhaps you changed Newsboat's `user-agent`?

> Interesting is, if I try to open the URL in the browser it tries to download the rss xml file. Maybe that is related

If you're running a recent Firefox, that's to be expected. FF used to ship a built-in RSS reader, now they simply treat RSS as a binary blob. Chromium does slightly better, displaying the XML in all its angle-bracket glory. But both download the correct feed for me.

**Comment by rnestler** [comment] 2019-10-30 11:40
Hmm I get the following in the log:
```
2096 [2019-10-30 12:37:04] DEBUG: View::run: event = r                                                    
2097 [2019-10-30 12:37:04] DEBUG: KeyMap::get_operation: keycode = r context = feedlist                   
2098 [2019-10-30 12:37:04] DEBUG: View::run: event = r op = 4                                             
2099 [2019-10-30 12:37:04] INFO: FeedListFormAction: reloading feed at position `1'                       
2100 [2019-10-30 12:37:04] DEBUG: Reloader::reload: pos = 1 max = 0                                       
2101 [2019-10-30 12:37:04] DEBUG: Reloader::reload: created parser                                        
2102 [2019-10-30 12:37:04] DEBUG: RssParser::download_http: user-agent = newsboat/r2.17.1 (Linux x86_64)  
2103 [2019-10-30 12:37:04] DEBUG: running query: SELECT lastmodified, etag FROM rss_feed WHERE rssurl = 'https://www.archlinux.org/feeds/news/';
2104 [2019-10-30 12:37:04] INFO: lastmodified_callback: lastmodified = 1572036292 etag = "b0686a3e05062e9c73d68b80e24fe840"
2105 [2019-10-30 12:37:04] DEBUG: Cache::fetch_lastmodified: t = 1572036292 etag = "b0686a3e05062e9c73d68b80e24fe840"
2106 [2019-10-30 12:37:04] DEBUG: handle_headers: got etag "b0686a3e05062e9c73d68b80e24fe840"             
2107 [2019-10-30 12:37:04] DEBUG: handle_headers: got last-modified  Fri, 25 Oct 2019 20:44:52 GMT^M      
2108  (1572036292)                                                                                        
2109 [2019-10-30 12:37:04] DEBUG: rsspp::Parser::parse_url: ret = 0 (No error)                            
2110 [2019-10-30 12:37:04] INFO: Parser::parse_url: retrieved data for https://www.archlinux.org/feeds/news/:
2111 [2019-10-30 12:37:04] DEBUG: RssParser::download_http: lm = 1572036292 etag = "b0686a3e05062e9c73d68b80e24fe840"
2112 [2019-10-30 12:37:04] DEBUG: RssParser::download_http: lastmodified old: 1572036292 new: 1572036292  
2113 [2019-10-30 12:37:04] DEBUG: RssParser::download_http: etag old: "b0686a3e05062e9c73d68b80e24fe840" new "b0686a3e05062e9c73d68b80e24fe840"
2114 [2019-10-30 12:37:04] INFO: Cache::update_lastmodified: both time and etag are empty, not updating anything
2115 [2019-10-30 12:37:04] DEBUG: RssParser::parse: http URL https://www.archlinux.org/feeds/news/, is_valid = true
2116 [2019-10-30 12:37:04] DEBUG: RssParser::parse: feed title = `' link = `https://www.archlinux.org/feeds/news/'
2117 [2019-10-30 12:37:04] DEBUG: Cache::remove_old_deleted_items: not cleaning up anything because last reload brought no new items (detected no changes)
2118 [2019-10-30 12:37:04] INFO: ScopeMeasure: function `Cache::remove_old_deleted_items' took 0.000022 s 
```

`2114 [2019-10-30 12:37:04] INFO: Cache::update_lastmodified: both time and etag are empty, not updating anything` seems to indicate the reason why it isn't updated.

**Comment by rnestler** [comment] 2019-10-30 13:50
Oh another thing I noticed: I also have the feed https://planet.archlinux.org/rss20.xml. This feed also has the official news posts from https://www.archlinux.org/feeds/news/ in it.
These posts seem to have the same `guid` in both rss feed (which makes sense, since they *are* the same posts).

**Comment by rnestler** [comment] 2019-10-30 14:13
OK, I can reproduce the issue now:
1. start fresh with both URLs in urls and refresh
    ```
    $ cat tmp_profile/urls
    https://planet.archlinux.org/rss20.xml news
    https://www.archlinux.org/feeds/news/ news
    $ newsboat --url-file tmp_profile/urls --config-file tmp_profile/config --cache-file tmp_profile/cache.db --log-level=6 --log-file=newsboat-fresh.log
    ```
    ![newsboat-1-fresh](https://user-images.githubusercontent.com/1435346/67865240-41ef2a00-fb27-11e9-826c-1d15109be89c.png)

2. mark an article in Arch Linux: Recent news updates as read
![newsboat-2-mark-read](https://user-images.githubusercontent.com/1435346/67865239-41569380-fb27-11e9-90ec-1cd84453a076.png)

3. refresh
![newsboat-3-refresh](https://user-images.githubusercontent.com/1435346/67865241-41ef2a00-fb27-11e9-9475-7286d213bc18.png)

4. close newsboat

5. open newsboat and refresh all -> double posts are gone.
![newsboat-4-posts-gone](https://user-images.githubusercontent.com/1435346/67865238-41569380-fb27-11e9-818e-88582aa40939.png)


It seems to be random in which feed the articles disappear, sometimes during reproducing it looked like they disappeared from the other feed.

**Comment by Minoru** [comment] 2019-10-30 18:56
> 2114 [2019-10-30 12:37:04] INFO: Cache::update_lastmodified: both time and etag are empty, not updating anything seems to indicate the reason why it isn't updated.

Yup. It means neither Last-Modified nor E-Tag changed relative to what Newsboat already had in the database. (A bit earlier in the log it shows a call to `Cache::fetch_lastmodified` with the values that are later shown in `handle_header`).

So it seems that you already had an entry in `rss_feed` table for "https://www.archlinux.org/feeds/news/", and you fetched it at least once recently (populating `lm` and `etag` fields), but there were no articles. Could it be that you had a `ignore-article` rule that matched them all, and `ignore-mode download` (the default)?

Even though you fixed this, it's be nice to get to the bottom of this to make sure it wasn't some obscure little corner case in Newsboat itself.

The other bug, where feeds steal items from each other, is an old one, and pretty thorny. You're spot on about GUIDs; for more details, you can read https://github.com/akrennmair/newsbeuter/issues/249.

**Comment by rnestler** [comment] 2019-10-31 11:56
> Even though you fixed this, it's be nice to get to the bottom of this to make sure it wasn't some obscure little corner case in Newsboat itself.

I think my issue was just the feed stealing. Probably at some point the https://planet.archlinux.org/rss20.xml feed stole all the https://www.archlinux.org/feeds/news/ entries. When opening the bug report, I didn't test with a fresh profile / cache, but just removed and added the feed and then refreshed all (since I have `auto-reload yes`) which probably resulted in the items getting stolen again.

So I think there is only really the "feeds steal items from each other" bug which I was experiencing.

**Comment by Minoru** [comment] 2019-11-01 19:25
I guess there's no way to reproduce the exact state that your cache.db was in for this to transpire, so I'll close this issue. Thanks for taking the time to file it!

**Closed by Minoru** 2019-11-01 19:25 UTC
Labels: bug, cannot-reproduce
