### ISSUE TITLE
Fail to copy url (link) spans line

### ISSUE THREAD

**Issue by pickfire** [newsboat/newsboat#718] opened 2020-01-14 11:47 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: newsboat 2.18.0 - https://newsboat.org/

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
#
# ~/.newsbeuter/config
#
# Author:  Ivan Tham <ivanthamjunhoe@gmail.com>
# Example: /usr/share/doc/newsbeuter/examples/config
#
# ~/.newsbeuter/urls are imported with newsbeuter -i blogroll.opml

#------------------------------------------------------------
# General
#------------------------------------------------------------

# Read
article-sort-order date-asc   # [date|title|flags|author|link|guid]-[asc|desc]

# Load
auto-reload yes               # [yes|no]
reload-time 120
reload-threads 3

# Item
max-items 30
keep-articles-days 15

# Info
notify-xterm no               # [yes|no]
notify-beep yes               # [yes|no]

# Cache
#cookie-cache "~/.cache/newsbeuter/cookies.txt"

# Notify
notify-format "%f unread feeds (%n unread articles)"
notify-program notify-send -t 10 "Newsbeuter"

# Ignore
ignore-article "*" "title =~ \"Sponsor\""
ignore-article "*" "title =~ \"Advertisement\""

#------------------------------------------------------------
# External
#------------------------------------------------------------

# HTML
browser xdg-open
html-renderer internal

# Pager
pager internal
text-width 80

#external-url-viewer ""

#------------------------------------------------------------
# Vi-keys binding
#------------------------------------------------------------

bind-key k up
bind-key j down

bind-key g home
bind-key G end

#------------------------------------------------------------
# Eye Candy
#------------------------------------------------------------

# Highlight
#highlight article "^Title:.*" color12
#highlight article "^Feed:.*"  color3
#highlight article "^(Link|Date):[^\n]+" color19
#highlight article "https?://[^ \n]+" color1

# Basic
#color background              color7 color0
#color listnormal              color7 color0
#color listfocus               color15 color4
color info                    color7 color0
#color article                 color7 color0
#color listnormal_unread       color15 color0 bold
#color listfocus_unread        color18 color3 bold

# Disable bars
show-keymap-hint no
swap-title-and-hints yes
```

Steps to reproduce the issue:

1. Have a feed that have very long link

2. Open that feed

3. Use mouse to double click to copy the link, link spans across links will be copied as multiple links probably because of newline insertion 

Expected the link to be able to copied and no newline is inserted even if the terminal is short.

**Other info you think is relevant**:

**Comment by Minoru** [comment] 2020-01-14 18:17
Closing as duplicate of #564. Note that you don't really need the mouse to click on URLs, [as our docs explain](https://newsboat.org/releases/2.18/docs/newsboat.html#_first_steps):

> Each URL in the article has a number next to it; to open it, type # and then the number, then press "Enter". For single-digit links, like 3, you can just press that number on the keyboard.

There's also [`show-urls`](https://newsboat.org/releases/2.18/docs/newsboat.html#show-urls) operation (bound to key `u` by default), which can even be customized via [`external-url-viewer` setting](https://newsboat.org/releases/2.18/docs/newsboat.html#external-url-viewer).

**Closed by Minoru** 2020-01-14 18:17 UTC

**Comment by pickfire** [comment] 2020-01-15 12:04
@Minoru Yes, but I am opening newsboat on another server through tmux and mosh.

**Comment by Minoru** [comment] 2020-01-15 18:08
Oh. You might be able to hack something together via `external-url-viewer`, but other than that, you're out of luck for now—you'll have to copy using mouse and re-assemble the links later.
