### ISSUE TITLE
Newsboat 2.20 requires space before semicolon in macros

### ISSUE THREAD

**Issue by pbakiewicz** [newsboat/newsboat#1013] opened 2020-06-21 13:25 UTC
It would be cool if I could via macro invoke custom bash script and pass url as an argument.

For instance, I've created a scripts which downloads a yt video and then translate English subtitles to language of choice and automatically play it out via mpv.

Simplified youtube-dl config:
```
-o ~/movies/%(id)s.%(ext)s
--write-sub
--exec 'trans_sub {} && mpv {}'
``` 
which trans_sub i my script translating and saving subtitles.

It work sreally well when I do:
`youtube-dl http://youtubevideourl.com`

But adding to newsboat config:
```
macro m set browser "youtube-dl %u"; open-in-browser ; set browser "elinks %u"
```
doesnt work at all.

Would be cool If I could do something like:
```
macro m execute "youtube-dl %u"
```

**Comment by Minoru** [comment] 2020-06-21 14:55
Hi! Sounds similar to #702. Does it work if you add a space before semicolons? Like this:

```
macro m set browser "youtube-dl %u" ; open-in-browser ; set browser "elinks %u"
```

**Comment by Minoru** [comment] 2020-06-22 13:47
#702 is related, but is not the root cause of this (and it actually asks to make the space optional). This bug is caused by https://github.com/newsboat/newsboat/commit/4b327fbff264c69bb78765304e16c2403c65b5e1, which made `utils::tokenize_quoted` drop the semicolon when tokenizing `set browser "youtube-dl %u";`. Reverting that commit fixes the issue, but I'm thinking of alternative solutions as well (because I don't want to re-introduce the second loop if one is sufficient).

Either way, I'll release Newsboat 2.20.1 in the middle of this week, which will contain a fix for this bug.

Sorry for the inconvenience!

**Comment by pbakiewicz** [comment] 2020-06-22 17:29
Unfortunately adding a space doesn't fix this. It actually downloads video to the right place but won't even start to translate subtitles, therefore this config line is not even executed:
`--exec 'trans_sub {} && mpv {}'`

From youtube-dl man:
```
--exec CMD
              Execute a command on the file after downloading and post-processing, similar to find's -exec syntax.
```

Also in theory after downlaod completes it should executes this CMD but it only returns back to my rss feed with 
`-Browser returned error code 1`

**Comment by Minoru** [comment] 2020-06-22 18:03
Okay, looks like I was a bit too hasty in attributing this to 2.20 breakage. A few additional questions then:

1. what Newsboat version are you running? You can find out with `newsboat --version`;
2. does `--exec 'true && mpv {}'` work?
3. does `--exec 'mpv {}'` work?
4. does `exec 'true'` work?

If none of that works, I'll need your `trans_sub` script, and a feed URL to test this on. Right now, I can't reproduce this because I can't re-create your configuration.

Just to make it clear: the proposed `execute` op would work exactly the same as `set browser … ; open-in-browser` dance, so I need to figure out why the existing approach doesn't work; just renaming it won't change anything.

**Closed** 2020-06-24 07:28 UTC
Labels: bug

**Comment by Minoru** [comment] 2020-06-24 07:29
I basically hijacked this issue, but please don't be deterred by that, @pbakiewicz: report the results of the tests I suggested above, and if it's a different bug, we can just make a new issue. Sorry about the confusion, but by this point it's easier to roll with it than to re-tag everything to point someplace else.
