### ISSUE TITLE
Can I get email notification if new RSS feeds are loaded with contents?

### ISSUE THREAD

**Issue by Blason** [newsboat/newsboat#2833] opened 2024-08-27 06:41 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
Version is 2.18.0

Can I get a update on emails if new feeds are found or observed?

**Comment by juntuu** [comment] 2024-08-28 18:20
You could use [notify-program](https://newsboat.org/releases/2.36/docs/newsboat.html#notify-program) config option.

**Comment by Minoru** [comment] 2024-08-28 18:35
I'll add one more pointer: [How to send a mail directly using Mutt?](https://unix.stackexchange.com/questions/560304/how-to-send-a-mail-directly-using-mutt). There are of course other programs too, e.g. `sendmail`.

Also, depending on what you want, `rss2email` might be a better fit than Newsboat.

I think this answers the question, so I'm going to close this, but feel free to comment below—we can always re-open.

**Closed by Minoru** 2024-08-28 18:35 UTC

**Comment by avidseeker** [comment] 2025-04-08 06:11
The problem is that newsboat scripting capabilities are too limited:

```
       -x command ..., --execute=command...
           Execute one or more commands to run Newsboat unattended.
           Currently available commands are reload and print-unread.
```

a `newsboat-sendmail` wrapper could only send how many are unread, but nothing about their content or headlines.
