### ISSUE TITLE
Enqueue fails with "Invalid URL: ''"

### ISSUE THREAD

**Issue by yggdr** [newsboat/newsboat#115] opened 2018-02-09 09:29 UTC
**Newsboat version (copy from `newsboat -v`)**: 2.10.2

Steps to reproduce the issue:
Replaced newsbeuter with newsboat.
Now I cannot enqueue video podcasts from feeds where it worked in newsbeuter previously; it fails with
`Invalid URL: ''`

My config:
`
auto-reload yes
reload-time 15
reload-threads 50
keep-articles-days 4
mark-as-read-on-hover yes

bind-key j down
bind-key k up
bind-key J next-feed
bind-key K prev-feed

browser "firefox %u"

notify-program /usr/local/bin/notify-send
notify-format "[FEEDS] new: %n in %f (total: %d in %D)"

color background green black
color listnormal white black
color listnormal_unread red black bold
color listfocus black color249 bold
color listfocus_unread color21 color249 bold
color info color50 black
color article color250 black

download-path "/storage/scratch/podcasts/%h/%n"
max-downloads 10
player "mpv"

articlelist-format "%4i  %D  %t %?T?[%T]"
`
Feed URL in question:
https://feeds.feedburner.com/BsdNowHd videos podcasts IT BSD

**Comment by Minoru** [comment] 2018-02-10 18:05
I reproduced this, but haven't yet looked into what might be causing it; will work on it later.

**Comment by Minoru** [comment] 2018-03-04 19:00
Thanks to a prod from @noctux, I finally looked into this and found that the issue was caused by my over-restrictive approach to what MIME types Newsboat enqueues. This [has already been fixed in the master branch](https://github.com/newsboat/newsboat/commit/2c347254f2ad2385a449fedb71fc58fe9d9e2384), and will be released at the end of March as part of Newsboat 2.10.3. Thank you for the report, and sorry for the regression!

**Closed by Minoru** 2018-03-04 19:00 UTC
Labels: bug
