### ISSUE TITLE
Article scroll is reset after opening a link in browser

### ISSUE THREAD

**Issue by genutis** [newsboat/newsboat#1463] opened 2021-02-07 22:50 UTC
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
newsboat 2.22.1 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2020 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2020 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

newsboat 2.22.1
System: Darwin 19.6.0 (x86_64)
Compiler: g++ Apple LLVM 12.0.0 (clang-1200.0.32.28)
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
libcurl: libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2 (compiled with 7.64.1)
SQLite: 3.34.0 (compiled with 3.34.0)
libxml2: compiled with 2.9.4

```

Steps to reproduce the issue:

1. Open RSS feed link with full article text (enough to scroll) and links

2. Scroll through the article then open link with the configured browser

3. Closing the browser returns the screen to the top of the article view despite the bottom righthand percentage indicating the previous screen position in the article (e.g. 27%). Scrolling again immediately changes this number to "Top."

I think it would be a little bit more convenient if newsboat could be configured to maintain the reading position in the article you were at when opening links in a browser (which are sometimes referenced within paragraphs and are convenient to open while reading), rather than returning to the top of the article.

**Comment by Minoru** [comment] 2021-02-08 15:45
Hey, thanks for the report! I reproduced this on the latest commit, https://github.com/newsboat/newsboat/commit/e80b0c1e9b32ce8205a60d5d0ca9e616b6d7d912.

`git-bisect` says this was broken in 2.22 by https://github.com/newsboat/newsboat/commit/9aa2e7e5edfb14d38b7a1cb9d8799edadcddb5be, but the real culprit is this line, introduced 14 years ago: https://github.com/newsboat/newsboat/blob/ea818e24a73a13577f8125e031b76f4bd3f83399/src/itemview_formaction.cpp#L114

This basically scrolls back to the top. As far as I understand, the purpose of it is to reset the scrolling when the ItemView changes, e.g. because of resizing the terminal, moving to a different item, switching to a source code view, etc. — but this code also runs when we switch to a different dialog and back (which is what 2.22 does while opening a link, and what a user could manually do by e.g. opening a help dialog).

Perhaps this line should be moved to init(), but I'm not entirely sure — maybe it should be controlled by a separate flag instead. I' working on a different thing right now, so this bug is up for grabs if anyone wants to dig any further.

**Comment by Minoru** [comment] 2021-02-10 13:53
A different manifestation of the same core issue: https://github.com/newsboat/newsboat/issues/1298

**Comment by jarbus** [comment] 2021-05-16 23:44
Still having this issue, any change it can be resolved?

**Comment by Minoru** [comment] 2021-05-17 12:33
I'm still busy with #1344, so I can't work on this right now. If you can, try adding a flag that controls when the aforementioned line is executed. #1298 lists some scenarios when it should and shouldn't be executed, but please look through the operations that article view supports and decide for each whether it should or shouldn't reset the position.

**Comment by jarbus** [comment] 2021-05-17 18:31
So I commented out
https://github.com/newsboat/newsboat/blob/7efb55f908d81b971c2bdfa2c37fd9c0e16aa8e5/src/itemviewformaction.cpp#L144
and recompiled. Seems to have fixed the issue. What I don't understand is why opening a URL triggers a re-draw in the first place. For me personally, I don't mind my position being wonky after a terminal resize, if it's too major of a displacement I can always manually go to the top of the article.

**Comment by Minoru** [comment] 2021-05-17 21:08
Commenting out the line breaks not just resizing, but also switching articles from within article view. If you open some article and then press J/K to go to the next/previous one, or n/p to a next/previous unread one, you'll notice that the article text didn't scroll to the beginning. There might be more issues like these; I just didn't go to the trouble of figuring out all of them, since for me it's enough that *one* use-case is broken to NAK the idea.

> What I don't understand is why opening a URL triggers a re-draw in the first place.

A non-answer is "that's how #1259 fixes a number of bugs". For an actual answer, you should read #63 (including the investigation in the comments) and then the description for #1259. I don't think I can write an accessible summary that's much shorter than links combined.

Admittedly, #1259 is something of a least-worst option, so if you see a better solution to those bugs, I'm all ears! Please comment under relevant issues, we can re-open them.

**Comment by jarbus** [comment] 2021-05-18 00:11
> If you open some article and then press J/K to go to the next/previous one, or n/p to a next/previous unread one, you'll notice that the article text didn't scroll to the beginning.

I tend to jump around my rss list instead of going in a linear order, so this is a tradeoff I'm willing to make for the time being. If that's the worst of it, fine by me :D Thanks for the work you do on this project

**Closed** 2021-05-18 22:01 UTC
Labels: bug
