### ISSUE TITLE
No Config File

### ISSUE THREAD

**Issue by HistoricGlint** [newsboat/newsboat#1045] opened 2020-06-27 16:12 UTC
newsboat 2.19.0
System: Linux 5.6.16-1-MANJARO (x86_64)
Compiler: g++ 9.3.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.70.0 OpenSSL/1.1.1g zlib/1.2.11 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh2/1.9.0 nghttp2/1.40.0 (compiled with 7.69.1)
SQLite: 3.32.2 (compiled with 3.31.1)
libxml2: compiled with 2.9.10

No config file on install. In .config, or .newsboat

I installed it from the AUR.

**Comment by Minoru** [comment] 2020-06-27 16:18
Hi! You're supposed to create one yourself. There is an example with all the options in the doc dir, usually /usr/share/doc/newsboat/.

Does that answer your question, @HistoricGlint?

**Comment by HistoricGlint** [comment] 2020-06-27 16:33
@Minoru Yes, that did answer the question. Could please you send your .config file? Thank you!

**Comment by Minoru** [comment] 2020-06-27 16:37
> Could you please send your .config file?

Here you go: https://github.com/Minoru/dotfiles/blob/master/.newsboat/config

Since the problem is resolved, I'm closing this. Thanks for using Newsboat!

**Closed by Minoru** 2020-06-27 16:37 UTC
Labels: question
